[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "toiftool"
version = "0.1.0"
description = ""
authors = [{ name = "matejcik", email = "ja@matejcik.cz" }]
requires-python = ">=3.8"
readme = "README.md"
dependencies = [
    "trezor>=0.13",
    "click>=7.0,<9.0",
    "Pillow>=10.0.1",
]

[project.scripts]
toiftool = "toiftool:cli"
