# Automatically generated by pb2py
# fmt: off
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

TIF_UNKNOWN: Literal[0] = 0
GTE: Literal[1] = 1
TIF_RESERVED: Literal[2] = 2
IOC: Literal[3] = 3
