# Automatically generated by pb2py
# fmt: off
# isort:skip_file

from trezor import utils

Bitcoin = 1
Crypto = 5
Shamir = 15
ShamirGroups = 16
PassphraseEntry = 17
if not utils.BITCOIN_ONLY:
    Bitcoin_like = 2
    Binance = 3
    Cardano = 4
    EOS = 6
    Ethereum = 7
    Lisk = 8
    Monero = 9
    NEM = 10
    Ripple = 11
    Stellar = 12
    Tezos = 13
    U2F = 14
