# Automatically generated by pb2py
# fmt: off
# isort:skip_file

from trezor import utils

UnexpectedMessage = 1
ButtonExpected = 2
DataError = 3
ActionCancelled = 4
PinExpected = 5
PinCancelled = 6
PinInvalid = 7
InvalidSignature = 8
ProcessError = 9
NotEnoughFunds = 10
NotInitialized = 11
PinMismatch = 12
WipeCodeMismatch = 13
InvalidSession = 14
Busy = 15
InvalidProtocol = 17
BufferError = 18
FirmwareError = 99
if utils.USE_THP:
    ThpUnallocatedSession = 16
