# Automatically generated by pb2py
# fmt: off
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

SPENDADDRESS: Literal[0] = 0
SPENDMULTISIG: Literal[1] = 1
EXTERNAL: Literal[2] = 2
SPENDWITNESS: Literal[3] = 3
SPENDP2SHWITNESS: Literal[4] = 4
