
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.block-buffer]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.bytecheck]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.bytecheck_derive]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.const-default]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.cty]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.embedded-alloc]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.17.1"
criteria = "safe-to-deploy"

[[exemptions.hmac-sha256]]
version = "1.1.14"
criteria = "safe-to-deploy"

[[exemptions.hmac-sha512]]
version = "1.1.12"
criteria = "safe-to-deploy"

[[exemptions.hybrid-array]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.keccak]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.189"
criteria = "safe-to-deploy"

[[exemptions.linked_list_allocator]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.munge]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.munge_macro]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.num_enum]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.num_enum_derive]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.107"
criteria = "safe-to-deploy"

[[exemptions.ptr_meta]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.ptr_meta_derive]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.47"
criteria = "safe-to-deploy"

[[exemptions.rancor]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.rend]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.rkyv]]
version = "0.8.17"
criteria = "safe-to-deploy"

[[exemptions.rkyv_derive]]
version = "0.8.17"
criteria = "safe-to-deploy"

[[exemptions.rlsf]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.23"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.sha3]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.simdutf8]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.119"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.20.1"
criteria = "safe-to-deploy"

[[exemptions.ufmt]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.ufmt-macros]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.ufmt-write]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"
