name: 'UI comment links'
description: 'Post URLs of HTML test reports to pull request discussion'
runs:
  using: composite
  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: fc
      if: github.event_name == 'pull_request'
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: ui-comment-${{ github.workflow }}

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v4
      if: github.event_name == 'pull_request'
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: ${{ env.PULL_COMMENT_PATH }}
        edit-mode: replace
