syntax = "proto2";
package hw.trezor.messages;

/**
 * Messages for Trezor communication
 */

/**
 * Mapping between Trezor wire identifier (uint) and a protobuf message
 */
enum MessageType {
    MessageType_ConfirmAction = 0;
    MessageType_ConfirmValue = 1;
    MessageType_ConfirmData = 2;
    MessageType_ConfirmProperties = 3;
    MessageType_ConfirmSummary = 4;
    MessageType_ShowNotice = 5;
    MessageType_ShowProgress = 6;
    MessageType_UiResult = 7;
    MessageType_ProgressTick = 8;
    MessageType_ProgressStep = 9;
    MessageType_ProgressEnd = 10;
}
