uses = [
    "backlight",
    "backup_ram",
    "boot_ucb",
    "button",
    "consumption_mask",
    "display",
    "dma2d",
    "framebuffer",
    "haptic",
    "hash_processor",
    "iwdg",
    "lockable_bootloader",
    "pvd",
    "rgb_led",
    "sdram",
    "secret",
    "secure_aes",
    "secmon_verification",
    "tamper",
    "telemetry",
    "touch",
]
