uses = [
    "backlight",
    "backup_ram",
    "ble",
    "boot_ucb",
    "button",
    "consumption_mask",
    "display",
    "framebuffer",
    "haptic",
    "hash_processor",
    "hw_revision",
    "iwdg",
    "layout_bolt",
    "layout_bolt_d001",
    "layout_bolt_d002",
    "layout_caesar",
    "layout_delizia",
    "layout_eckhart",
    "lockable_bootloader",
    "mcu_attestation",
    "nfc",
    "nrf",
    "optiga",
    "power_manager",
    "rgb_led",
    "rtc",
    "sbu",
    "sd_card",
    "sdram",
    "secret",
    "secmon_header",
    "secure_aes",
    "smp",
    "storage_hw_key",
    "suspend",
    "tamper",
    "telemetry",
    "touch",
    "tropic",
]
