extends: default

ignore: |
  /.venv
  vendor/
  /common/defs/ethereum/chains/
  /common/defs/ethereum/tokens/
  /nordic/

rules:
  # fix for truthy warning on github action files
  truthy:
    allowed-values: ['true', 'false', 'on']
  # skip line length
  line-length: disable
  # skip "---" at the beginning
  document-start: disable
  comments-indentation: disable
  indentation:
    spaces: 2
