# generated using gen_nem_mosaics.py from trezor-common nem_mosaics.json - do not edit directly!

mosaics = [
    {
        "name": "XEM",
        "ticker": " XEM",
        "namespace": "nem",
        "mosaic": "xem",
        "divisibility": 6,
    },
    {
        "name": "DIMCOIN",
        "ticker": " DIM",
        "namespace": "dim",
        "mosaic": "coin",
        "divisibility": 6,
        "levy": "MosaicLevy_Percentile",
        "fee": 10,
        "levy_namespace": "dim",
        "levy_mosaic": "coin",
        "networks": [104],
    },
    {
        "name": "DIM TOKEN",
        "ticker": " DIMTOK",
        "namespace": "dim",
        "mosaic": "token",
        "divisibility": 6,
        "networks": [104],
    },
    {
        "name": "Breeze Token",
        "ticker": " BREEZE",
        "namespace": "breeze",
        "mosaic": "breeze-token",
        "divisibility": 0,
        "networks": [104],
    },
    {
        "name": "PacNEM Game Credits",
        "ticker": " PAC:HRT",
        "namespace": "pacnem",
        "mosaic": "heart",
        "divisibility": 0,
        "networks": [104],
    },
    {
        "name": "PacNEM Score Tokens",
        "ticker": " PAC:CHS",
        "namespace": "pacnem",
        "mosaic": "cheese",
        "divisibility": 6,
        "levy": "MosaicLevy_Percentile",
        "fee": 100,
        "levy_namespace": "nem",
        "levy_mosaic": "xem",
        "networks": [104],
    },
]
