#ifndef _STM32F429I_DISC1_H
#define _STM32F429I_DISC1_H

#define HSE_8MHZ

#define MAX_DISPLAY_RESX 240
#define MAX_DISPLAY_RESY 320
#define DISPLAY_RESX 240
#define DISPLAY_RESY 320

#define USE_I2C 1
#define USE_TOUCH 1
#define USE_SDRAM 1
#define USE_RGB_COLORS 1

#include "displays/ltdc.h"

#define I2C_COUNT 1
#define I2C_INSTANCE_1 I2C3
#define I2C_INSTANCE_1_CLK_EN __HAL_RCC_I2C3_CLK_ENABLE
#define I2C_INSTANCE_1_CLK_DIS __HAL_RCC_I2C3_CLK_DISABLE
#define I2C_INSTANCE_1_PIN_AF GPIO_AF4_I2C3
#define I2C_INSTANCE_1_SDA_PORT GPIOC
#define I2C_INSTANCE_1_SDA_PIN GPIO_PIN_9
#define I2C_INSTANCE_1_SDA_CLK_EN __HAL_RCC_GPIOC_CLK_ENABLE
#define I2C_INSTANCE_1_SCL_PORT GPIOA
#define I2C_INSTANCE_1_SCL_PIN GPIO_PIN_8
#define I2C_INSTANCE_1_SCL_CLK_EN __HAL_RCC_GPIOA_CLK_ENABLE
#define I2C_INSTANCE_1_RESET_FLG RCC_APB1RSTR_I2C3RST

#define TOUCH_I2C_NUM 0

#endif  //_STM32F429I_DISC1_H
