// This file is generated by core/tools/codegen/gen_font.py

#include <stdint.h>
#include "fonts.h"

#if TREZOR_FONT_BPP != 4
#error Wrong TREZOR_FONT_BPP (expected 4)
#endif

extern const font_info_t Font_TTHoves_DemiBold_21_info;
