header = "T3T1/boards/trezor_t3t1_revE.h"
emulator_header = "T3T1/boards/t3t1-unix.h"

[display]
driver = "io/display_st7789"
panel = "io/display_panel_lx154a2482"

[backlight]
driver = "io/backlight_tps61043"

[touch]
driver = "io/touch_ft6x36"
panel = "io/touch_panel_lx154a2422cpt23"

[haptic]

[sd_card]

[optiga]

[sbu]
