#ifndef BOARDS_T3T1_UNIX_H
#define BOARDS_T3T1_UNIX_H

#define WINDOW_WIDTH 400
#define WINDOW_HEIGHT 600
#define TOUCH_OFFSET_X 80
#define TOUCH_OFFSET_Y 102

#define ORIENTATION_NSEW 1

#define BACKGROUND_FILE "T3T1/background_T3T1.h"
#define BACKGROUND_NAME background_T3T1_jpg

#endif  // BOARDS_T3T1_UNIX_H
