# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class ApplyFlags(p.MessageType):
    MESSAGE_WIRE_TYPE = 28

    def __init__(
        self,
        flags: int = None,
    ) -> None:
        self.flags = flags

    @classmethod
    def get_fields(cls):
        return {
            1: ('flags', p.UVarintType, 0),
        }
