# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class MoneroAddress(p.MessageType):
    MESSAGE_WIRE_TYPE = 541

    def __init__(
        self,
        address: bytes = None,
    ) -> None:
        self.address = address

    @classmethod
    def get_fields(cls):
        return {
            1: ('address', p.BytesType, 0),
        }
