# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class NEMSignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 70

    def __init__(
        self,
        data: bytes = None,
        signature: bytes = None,
    ) -> None:
        self.data = data
        self.signature = signature

    @classmethod
    def get_fields(cls):
        return {
            1: ('data', p.BytesType, 0),
            2: ('signature', p.BytesType, 0),
        }
