# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class PinMatrixAck(p.MessageType):
    MESSAGE_WIRE_TYPE = 19

    def __init__(
        self,
        pin: str = None,
    ) -> None:
        self.pin = pin

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('pin', p.UnicodeType, 0),  # required
        }
