# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .TronProposalParameters import TronProposalParameters

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class TronProposalCreateContract(p.MessageType):

    def __init__(
        self,
        parameters: List[TronProposalParameters] = None,
    ) -> None:
        self.parameters = parameters if parameters is not None else []

    @classmethod
    def get_fields(cls):
        return {
            1: ('parameters', TronProposalParameters, p.FLAG_REPEATED),
        }
