[package]
name = "api"
version = "0.1.0"
edition = "2024"
links = "api"

[build-dependencies]
color-eyre.workspace = true
xbuild.workspace = true
bindgen.workspace = true

[dependencies]
lock_api.workspace = true
spin = { workspace = true, features = ["lock_api"] }
stabby.workspace = true
talc.workspace = true
trezor-app-sdk.workspace = true

crypto.workspace = true
models.workspace = true
rtl.workspace = true
sec.workspace = true
sys.workspace = true
io.workspace = true

[features]

test = []

default = ["io/ipc", "io/app_loading"]
