VSYS_UNITY = 100000000
VSYS_ADDRESS_VERSION = 5

MAINNET_CHAIN_ID = 'M'
TESTNET_CHAIN_ID = 'T'

PROTOCOL = 'v.systems'

OPC_ACCOUNT = 'account'
OPC_TX = 'transaction'
OPC_SIGN = 'signature'

SUPPORT_API_VER = 2
ACCOUNT_API_VER = 1
SIGN_API_VER = 1

PAYMENT_TX_TYPE = 2
LEASE_TX_TYPE = 3
LEASE_CANCEL_TX_TYPE = 4
