// This file is auto-generated by `core/tools/generate_certificates.py`.
// Do not edit this file directly. Instead, run `make gen` or `make certs`
// in the root directory.

#define MCU_DEVICE_CERT \
  {                     \
      0x30, 0x00,       \
  }
