mcu = "stm32u58"
default_board = "revB"
emulator_board = "unix"

features = [
    "consumption_mask",
    "hash_processor",
    "hw_revision",
    "lockable_bootloader",
    "pvd",
    "secret",
    "secure_aes",
    "framebuffer",
    "secure_mode",
    "storage_hw_key",
    "tamper",
    "layout_caesar",
]
