mcu = "stm32f427"
default_board = "hw"

features = [
    "dma2d",
    "pvd",
    "secure_mode",
    "layout_bolt",
    "display_rgb565",

    # Legacy coin support
    "decred",
    "eos",
    "nem",
]
