// This file is generated by core/tools/codegen/gen_font.py

#include <stdint.h>
#include "fonts_types.h"

#if TREZOR_FONT_BPP != 1
#error Wrong TREZOR_FONT_BPP (expected 1)
#endif

#define Font_PixelOperator_Bold_8_MAX_HEIGHT 8
extern const font_info_t Font_PixelOperator_Bold_8_info;
#define Font_PixelOperator_Bold_8_upper_MAX_HEIGHT 8
extern const font_info_t Font_PixelOperator_Bold_8_upper_info;
