// This file is generated by core/tools/codegen/gen_font.py

#include <stdint.h>
#include "fonts_types.h"

#if TREZOR_FONT_BPP != 4
#error Wrong TREZOR_FONT_BPP (expected 4)
#endif

#define Font_TTHoves_Bold_17_upper_MAX_HEIGHT 18
extern const font_info_t Font_TTHoves_Bold_17_upper_info;
