uses = [
    "backup_ram",
    "boot_ucb",
    "ext_flash_otfdec",
    "consumption_mask",
    "hash_processor",
    "lockable_bootloader",
    "mcu_attestation",
    "nrf_auth",
    "optiga",
    "secret",
    "secure_aes",
    "suspend",
    "tamper",
    "telemetry",
    "tropic",
]

elf_sections = [".secmon_header", ".flash", ".data", ".gnu.sgstubs"]
