# Project-specific configuration

# Filter of the model/board defined features for this specific project
uses = [
    "backup_ram",
    "boot_ucb",
    "consumption_mask",
    "hash_processor",
    "lockable_bootloader",
    "mcu_attestation",
    "nrf_auth",
    "optiga",
    "secret",
    "secure_aes",
    "suspend",
    "tamper",
    "telemetry",
    "tropic",
]

# ELF sections to be included in the final binary.
# The order of sections is important.
elf_sections = [".secmon_header", ".flash", ".data", ".gnu.sgstubs"]

# xtask build options mapped to the cargo features
[build-options]
asan                          = { true = ["asan"] }
bootloader-devel              = { true = ["bootloader_devel"] }
btc-only                      = { false = ["universal_fw"] }
dbg-console                   = { swo = ["dbg_console_swo"], system-view = ["dbg_console_system_view"] }
force-bootloader-upgrade      = { true = ["force_bootloader_upgrade"] }
production                    = { true = ["production"] }
pyopt                         = { false = ["optiga_testing"] }
storage-insecure-testing-mode = { true = ["storage_insecure_testing_mode"] }
unsafe-fw                     = { true = ["unsafe_fw"] }
