[tool.poetry]
name = "trezor-pylint-plugin"
version = "0.1.0"
description = ""
authors = ["matejcik <ja@matejcik.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pylint = "*"
astroid = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
