# This file is part of the Trezor project.
#
# Copyright (C) 2012-2019 SatoshiLabs and contributors
#
# This library is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License version 3
# as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the License along with this library.
# If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.

import pytest

from trezorlib.cardano import (
    NETWORK_IDS,
    PROTOCOL_MAGICS,
    create_address_parameters,
    get_address,
)
from trezorlib.messages import CardanoAddressType

from ..common import MNEMONIC12

SHELLEY_TEST_VECTORS_MNEMONIC = (
    "test walk nut penalty hip pave soap entry language right filter choice"
)


@pytest.mark.altcoin
@pytest.mark.cardano
@pytest.mark.skip_t1  # T1 support is not planned
@pytest.mark.parametrize(
    "spending_path,protocol_magic,expected_address",
    [
        # mainnet
        (
            "m/44'/1815'/0'/0/0",
            PROTOCOL_MAGICS["mainnet"],
            "Ae2tdPwUPEZLCq3sFv4wVYxwqjMH2nUzBVt1HFr4v87snYrtYq3d3bq2PUQ",
        ),
        (
            "m/44'/1815'/0'/0/1",
            PROTOCOL_MAGICS["mainnet"],
            "Ae2tdPwUPEZEY6pVJoyuNNdLp7VbMB7U7qfebeJ7XGunk5Z2eHarkcN1bHK",
        ),
        (
            "m/44'/1815'/0'/0/2",
            PROTOCOL_MAGICS["mainnet"],
            "Ae2tdPwUPEZ3gZD1QeUHvAqadAV59Zid6NP9VCR9BG5LLAja9YtBUgr6ttK",
        ),
        # testnet
        # data generated by code under test
        (
            "m/44'/1815'/0'/0/0",
            PROTOCOL_MAGICS["testnet"],
            "2657WMsDfac5vydkak9a7BqGrsLqBzB7K3vT55rucZKYDmVnUCf6hXAFkZSTcUx7r",
        ),
        (
            "m/44'/1815'/0'/0/1",
            PROTOCOL_MAGICS["testnet"],
            "2657WMsDfac61ebUDw53WUX49Dcfya8S8G7iYbhN4nP8JSFuh38T1LuFax1bUnhxA",
        ),
        (
            "m/44'/1815'/0'/0/2",
            PROTOCOL_MAGICS["testnet"],
            "2657WMsDfac5PMpEsxc1md3pgZKUZRZ11MUK8tjkDHBQG9b3TMBsTQc4PmmumVrcn",
        ),
    ],
)
@pytest.mark.setup_client(mnemonic=MNEMONIC12)
def test_cardano_get_address(client, spending_path, protocol_magic, expected_address):
    address = get_address(
        client,
        address_parameters=create_address_parameters(
            address_type=CardanoAddressType.BYRON, spending_key_path_str=spending_path,
        ),
        protocol_magic=protocol_magic,
        network_id=NETWORK_IDS["mainnet"],
    )
    assert address == expected_address


@pytest.mark.altcoin
@pytest.mark.cardano
@pytest.mark.skip_t1  # T1 support is not planned
@pytest.mark.parametrize(
    "spending_path, staking_path, network_id, expected_address",
    [
        # data generated with code under test
        (
            "m/1852'/1815'/4'/0/0",
            "m/1852'/1815'/4'/2/0",
            NETWORK_IDS["mainnet"],
            "addr1q84sh2j72ux0l03fxndjnhctdg7hcppsaejafsa84vh7lwgmcs5wgus8qt4atk45lvt4xfxpjtwfhdmvchdf2m3u3hlsd5tq5r",
        ),
        (
            "m/1852'/1815'/4'/0/0",
            "m/1852'/1815'/4'/2/0",
            NETWORK_IDS["testnet"],
            "addr_test1qr4sh2j72ux0l03fxndjnhctdg7hcppsaejafsa84vh7lwgmcs5wgus8qt4atk45lvt4xfxpjtwfhdmvchdf2m3u3hlswzkqcu",
        ),
    ],
)
@pytest.mark.setup_client(mnemonic=SHELLEY_TEST_VECTORS_MNEMONIC)
def test_cardano_get_base_address(
    client, spending_path, staking_path, network_id, expected_address
):
    address = get_address(
        client,
        address_parameters=create_address_parameters(
            address_type=CardanoAddressType.BASE,
            spending_key_path_str=spending_path,
            staking_key_path_str=staking_path,
        ),
        protocol_magic=PROTOCOL_MAGICS["mainnet"],
        network_id=network_id,
    )
    assert address == expected_address


@pytest.mark.altcoin
@pytest.mark.cardano
@pytest.mark.skip_t1  # T1 support is not planned
@pytest.mark.parametrize(
    "spending_path, staking_key_hash, network_id, expected_address",
    [
        # data generated with code under test
        (
            "m/1852'/1815'/4'/0/0",
            "1bc428e4720702ebd5dab4fb175324c192dc9bb76cc5da956e3c8dff",
            NETWORK_IDS["mainnet"],
            "addr1q84sh2j72ux0l03fxndjnhctdg7hcppsaejafsa84vh7lwgmcs5wgus8qt4atk45lvt4xfxpjtwfhdmvchdf2m3u3hlsd5tq5r",
        ),
        (
            "m/1852'/1815'/4'/0/0",
            "1bc428e4720702ebd5dab4fb175324c192dc9bb76cc5da956e3c8dff",
            NETWORK_IDS["testnet"],
            "addr_test1qr4sh2j72ux0l03fxndjnhctdg7hcppsaejafsa84vh7lwgmcs5wgus8qt4atk45lvt4xfxpjtwfhdmvchdf2m3u3hlswzkqcu",
        ),
        # staking key hash not owned - derived with "all all..." mnenomnic, data generated with code under test
        (
            "m/1852'/1815'/4'/0/0",
            "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
            NETWORK_IDS["mainnet"],
            "addr1q84sh2j72ux0l03fxndjnhctdg7hcppsaejafsa84vh7lwgj922xhxkn6twlq2wn4q50q352annk3903tj00h45mgfmsxrrvc2",
        ),
        (
            "m/1852'/1815'/0'/0/0",
            "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
            NETWORK_IDS["testnet"],
            "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzersj922xhxkn6twlq2wn4q50q352annk3903tj00h45mgfmses0nu5",
        ),
        (
            "m/1852'/1815'/4'/0/0",
            "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
            NETWORK_IDS["testnet"],
            "addr_test1qr4sh2j72ux0l03fxndjnhctdg7hcppsaejafsa84vh7lwgj922xhxkn6twlq2wn4q50q352annk3903tj00h45mgfms947v54",
        ),
    ],
)
@pytest.mark.setup_client(mnemonic=SHELLEY_TEST_VECTORS_MNEMONIC)
def test_cardano_get_base_address_with_staking_key_hash(
    client, spending_path, staking_key_hash, network_id, expected_address
):
    # data form shelley test vectors
    address = get_address(
        client,
        address_parameters=create_address_parameters(
            address_type=CardanoAddressType.BASE,
            spending_key_path_str=spending_path,
            staking_key_hash_str=staking_key_hash,
        ),
        protocol_magic=PROTOCOL_MAGICS["mainnet"],
        network_id=network_id,
    )
    assert address == expected_address


@pytest.mark.altcoin
@pytest.mark.cardano
@pytest.mark.skip_t1  # T1 support is not planned
@pytest.mark.parametrize(
    "spending_path, network_id, expected_address",
    [
        # data generated with code under test
        (
            "m/1852'/1815'/0'/0/0",
            NETWORK_IDS["mainnet"],
            "addr1vx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzers66hrl8",
        ),
        (
            "m/1852'/1815'/0'/0/0",
            NETWORK_IDS["testnet"],
            "addr_test1vz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzerspjrlsz",
        ),
    ],
)
@pytest.mark.setup_client(mnemonic=SHELLEY_TEST_VECTORS_MNEMONIC)
def test_cardano_get_enterprise_address(
    client, spending_path, network_id, expected_address
):
    address = get_address(
        client,
        address_parameters=create_address_parameters(
            address_type=CardanoAddressType.ENTERPRISE,
            spending_key_path_str=spending_path,
        ),
        protocol_magic=PROTOCOL_MAGICS["mainnet"],
        network_id=network_id,
    )
    assert address == expected_address


@pytest.mark.altcoin
@pytest.mark.cardano
@pytest.mark.skip_t1  # T1 support is not planned
@pytest.mark.parametrize(
    "spending_path, block_index, tx_index, certificate_index, network_id, expected_address",
    [
        # data generated with code under test
        (
            "m/1852'/1815'/0'/0/0",
            1,
            2,
            3,
            NETWORK_IDS["mainnet"],
            "addr1gx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzerspqgpse33frd",
        ),
        (
            "m/1852'/1815'/0'/0/0",
            24157,
            177,
            42,
            NETWORK_IDS["testnet"],
            "addr_test1gz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer5ph3wczvf2pfz4ly",
        ),
    ],
)
@pytest.mark.setup_client(mnemonic=SHELLEY_TEST_VECTORS_MNEMONIC)
def test_cardano_get_pointer_address(
    client,
    spending_path,
    block_index,
    tx_index,
    certificate_index,
    network_id,
    expected_address,
):
    address = get_address(
        client,
        address_parameters=create_address_parameters(
            address_type=CardanoAddressType.POINTER,
            spending_key_path_str=spending_path,
            block_index=block_index,
            tx_index=tx_index,
            certificate_index=certificate_index,
        ),
        protocol_magic=PROTOCOL_MAGICS["mainnet"],
        network_id=network_id,
    )
    assert address == expected_address


@pytest.mark.altcoin
@pytest.mark.cardano
@pytest.mark.skip_t1  # T1 support is not planned
@pytest.mark.parametrize(
    "spending_path, network_id, expected_address",
    [
        # data generated with code under test
        (
            "m/1852'/1815'/0'/2/0",
            NETWORK_IDS["mainnet"],
            "stake1uyevw2xnsc0pvn9t9r9c7qryfqfeerchgrlm3ea2nefr9hqxdekzz",
        ),
        (
            "m/1852'/1815'/0'/2/0",
            NETWORK_IDS["testnet"],
            "stake_test1uqevw2xnsc0pvn9t9r9c7qryfqfeerchgrlm3ea2nefr9hqp8n5xl",
        ),
    ],
)
@pytest.mark.setup_client(mnemonic=SHELLEY_TEST_VECTORS_MNEMONIC)
def test_cardano_get_reward_address(
    client, spending_path, network_id, expected_address
):
    address = get_address(
        client,
        address_parameters=create_address_parameters(
            address_type=CardanoAddressType.REWARD, spending_key_path_str=spending_path,
        ),
        protocol_magic=PROTOCOL_MAGICS["mainnet"],
        network_id=network_id,
    )
    assert address == expected_address
