#ifndef BOARDS_T3W1_UNIX_H
#define BOARDS_T3W1_UNIX_H

#define WINDOW_WIDTH 600
#define WINDOW_HEIGHT 800
#define TOUCH_OFFSET_X 107
#define TOUCH_OFFSET_Y 53

#define BTN_POWER_KEY SDLK_p

#define ORIENTATION_NS 1

#define LED_OFFSET_Y -8

#define FOREGROUND_FILE "T3W1/foreground_T3W1.h"
#define FOREGROUND_NAME foreground_T3W1_png

#endif  // BOARDS_T3W1_UNIX_H
