--- a/unix/Makefile
+++ b/unix/Makefile
@@ -103,6 +103,13 @@ ifeq ($(MICROPY_PY_THREAD),1)
 CFLAGS_MOD += -DMICROPY_PY_THREAD=1 -DMICROPY_PY_THREAD_GIL=0
 LDFLAGS_MOD += -lpthread
 endif
+ifeq ($(MICROPY_PY_TREZORUI),1)
+ifeq ($(TREZORUI_NOUI),1)
+CFLAGS_MOD += -DTREZORUI_NOUI=1
+else
+LDFLAGS_MOD += -lSDL2 -lSDL2_image
+endif
+endif
 
 ifeq ($(MICROPY_PY_FFI),1)
 
