CacheDir('build_cache')

# pylint: disable=E0602
Decider('content-timestamp')
SetOption('max_drift', 10)
SetOption('implicit_cache', 1)

SConscript('SConscript.boardloader', variant_dir='build/boardloader', duplicate=False)
SConscript('SConscript.bootloader', variant_dir='build/bootloader', duplicate=False)
SConscript('SConscript.bootloader_ci', variant_dir='build/bootloader_ci', duplicate=False)
SConscript('SConscript.bootloader_emu', variant_dir='build/bootloader_emu', duplicate=False)
SConscript('SConscript.secmon', variant_dir='build/secmon', duplicate=False)
SConscript('SConscript.kernel', variant_dir='build/kernel', duplicate=False)
SConscript('SConscript.firmware', variant_dir='build/firmware', duplicate=False)
SConscript('SConscript.prodtest', variant_dir='build/prodtest', duplicate=False)
SConscript('SConscript.prodtest_emu', variant_dir='build/prodtest_emu', duplicate=False)
SConscript('SConscript.unix', variant_dir='build/unix', duplicate=False)

if ARGUMENTS.get('QUIET_MODE', '0') == '1':
    import sys
    if sys.stdout.isatty():
        Progress('$TARGET\r', overwrite=True)
