use anyhow::{Result, anyhow};
use clap::{Args, Parser, Subcommand, ValueEnum};

pub use crate::model::Model;

#[derive(ValueEnum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum Project {
    Bootloader,
    Boardloader,
    #[value(name = "bootloader_ci")]
    BootloaderCi,
    Firmware,
    Prodtest,
    Kernel,
    Secmon,
}

impl Project {
    /// The Rust package name used for cargo commands
    pub fn package_name(self, emulator: bool) -> &'static str {
        match self {
            Project::Bootloader => "bootloader",
            Project::Boardloader => "boardloader",
            Project::BootloaderCi => "bootloader_ci",
            Project::Firmware => {
                if emulator {
                    "unix"
                } else {
                    "firmware"
                }
            }
            Project::Prodtest => "prodtest",
            Project::Kernel => "kernel",
            Project::Secmon => "secmon",
        }
    }

    /// The linker binary type used by `build_and_link()`. This determines
    /// the `.map` filename generated by the linker.
    pub fn binary_name(self) -> &'static str {
        match self {
            Project::Bootloader => "bootloader",
            Project::BootloaderCi => "bootloader_ci",
            Project::Boardloader => "boardloader",
            Project::Firmware => "firmware",
            Project::Prodtest => "prodtest",
            Project::Kernel => "kernel",
            Project::Secmon => "secmon",
        }
    }

    /// The artifact name used for collected build outputs.
    /// Appends `-emu` for emulator builds.
    pub fn artifact_name(self, emulator: bool) -> String {
        let base = self.binary_name();
        if emulator {
            format!("{base}-emu")
        } else {
            base.to_string()
        }
    }

    /// Get symbol from memory.ld used as start address for flashing
    pub fn flash_start_symbol(self) -> Result<&'static str> {
        let symbol = match self {
            Project::Boardloader => "BOARDLOADER_START",
            Project::Bootloader | Project::BootloaderCi => "BOOTLOADER_START",
            Project::Firmware | Project::Prodtest => "FIRMWARE_START",
            _ => return Err(anyhow!("Flashing {:?} is not supported", self)),
        };
        Ok(symbol)
    }

    /// Returns the next project in the dependency chain,
    /// (e.g. Firmware -> Kernel -> Secmon)
    pub fn dependency(self, model: Model) -> Result<Option<Project>> {
        match self {
            Project::Firmware => Ok(Some(Project::Kernel)),
            Project::Kernel => {
                let has_secmon = model.config()?.secmon;
                Ok(if has_secmon {
                    Some(Project::Secmon)
                } else {
                    None
                })
            }
            _ => Ok(None),
        }
    }

    /// Returns whether the project can be flashed to a device
    /// using the `flash` subcommand.
    pub fn flashable(self) -> bool {
        self.flash_start_symbol().is_ok()
    }

    /// Returns whether the project can be uploaded to a device
    /// using the `upload` subcommand.
    pub fn uploadable(self) -> bool {
        matches!(self, Project::Firmware | Project::Prodtest)
    }
}

#[derive(ValueEnum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConsoleType {
    Vcp,
    Swo,
    SystemView,
}

#[derive(Parser, Debug)]
#[command(name = "xtask")]
#[command(about = "Trezor workspace automation tasks")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Cmd,
}

#[derive(Subcommand, Debug)]
pub enum Cmd {
    /// Build a project with the specified configuration
    Build(BuildArgs),
    /// Run clippy command with the specified configuration
    Clippy(BuildArgs),
    /// Run check command with the specified configuration
    Check(BuildArgs),
    /// Run tests of specified package
    Test(TestArgs),
    /// Clean build artifacts
    Clean,
    /// Format code with rustfmt
    Fmt,
    /// Flash firmware to device using OpenOCD
    Flash(FlashArgs),
    /// Erase flash or part of it using OpenOCD
    FlashErase(FlashEraseArgs),
    /// Reset the connected device using OpenOCD
    Reset(ResetArgs),
    /// Upload firmware to device
    Upload(UploadArgs),
    /// Combine multiple firmware projects into a single binary for flashing
    Combine(CombineArgs),
}

#[derive(Args, Debug, Clone)]
#[command(override_usage = "xtask build <PROJECT> --model <MODEL> [OPTIONS]")]
pub struct BuildArgs {
    pub project: Project,

    /// Build target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,

    /// Use emulator build
    #[arg(long, short = 'e')]
    pub emulator: bool,

    /// Enable debug build
    #[arg(long, short = 'd', num_args = 0..=1, default_missing_value = "true")]
    pub debug: Option<bool>,

    /// Debug console backend
    #[arg(long)]
    pub dbg_console: Option<ConsoleType>,

    /// Build Bitcoin-only firmware
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub btc_only: Option<bool>,

    /// Enable production build
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub production: Option<bool>,

    /// Force bootloader upgrade
    #[arg(long)]
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub force_bootloader_upgrade: Option<bool>,

    /// Use dev bootloader
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub bootloader_devel: Option<bool>,

    /// Enable unsafe firmware features
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub unsafe_fw: Option<bool>,

    /// Embed frozen MicroPython modules
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub frozen: Option<bool>,

    /// Include MicroPython source lines
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub source_lines: Option<bool>,

    /// Optimize MicroPython bytecode
    #[arg(long, num_args = 0..=1, default_missing_value = "true", overrides_with = "pyopt")]
    pub pyopt: Option<bool>,

    /// Enable Micropython memory performance measurements
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub mem_perf: Option<bool>,

    /// Enable debug link
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub debug_link: Option<bool>,

    /// Enable N4W1 support
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub n4w1: Option<bool>,

    /// Disable UI animations
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub disable_animation: Option<bool>,

    /// Show UI perf overlay
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub perf_overlay: Option<bool>,

    /// Include crypto benchmarks
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub benchmark: Option<bool>,

    /// Log stack usage
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub log_stack_usage: Option<bool>,

    /// Use blocking VCP writes, in order to allow reliable debug data
    /// transmission over VCP. Disabled by default, to prevent debug
    /// firmware from getting stuck while writing log messages (if the host
    /// is not reading them).
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub block_on_vcp: Option<bool>,

    /// Enable Address Sanitizer (ASAN) instrumentation
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub asan: Option<bool>,

    /// Enable external app loading
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub apps: Option<bool>,

    /// Disable OPTIGA support
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub disable_optiga: Option<bool>,

    /// Board revision to build for (defaults to model's default_board)
    #[arg(long, short = 'b')]
    pub board: Option<String>,

    /// Disable TROPIC support
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub disable_tropic: Option<bool>,

    /// Enable insecure storage test mode
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub storage_insecure_testing_mode: Option<bool>,

    /// Emits memory analysis output (type sizes and stack sizes)
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    pub emit_memory_analysis: Option<bool>,

    /// Output cargo timings
    #[arg(long)]
    pub timings: bool,

    /// Enable verbose output
    #[arg(long)]
    pub verbose: bool,
}

#[derive(Debug, Clone)]
pub struct ResolvedBuildArgs {
    pub project: Project,
    pub model: Model,
    pub emulator: bool,
    pub debug: bool,
    pub dbg_console: Option<ConsoleType>,
    pub btc_only: bool,
    pub production: bool,
    pub force_bootloader_upgrade: bool,
    pub bootloader_devel: bool,
    pub unsafe_fw: bool,
    pub frozen: bool,
    pub source_lines: bool,
    pub pyopt: bool,
    pub mem_perf: bool,
    pub debug_link: bool,
    pub n4w1: bool,
    pub disable_animation: bool,
    pub perf_overlay: bool,
    pub benchmark: bool,
    pub log_stack_usage: bool,
    pub block_on_vcp: bool,
    pub asan: bool,
    pub apps: bool,
    pub disable_optiga: bool,
    pub board: Option<String>,
    pub disable_tropic: bool,
    pub storage_insecure_testing_mode: bool,
    pub emit_memory_analysis: bool,
    pub timings: bool,
    pub verbose: bool,
}

impl ResolvedBuildArgs {
    pub fn from_build_args(args: &BuildArgs) -> Self {
        let pyopt = args.pyopt.unwrap_or(true);
        Self {
            project: args.project,
            model: args.model,
            emulator: args.emulator,
            debug: args.debug.unwrap_or(args.emulator),
            dbg_console: args.dbg_console,
            btc_only: args.btc_only.unwrap_or(false),
            production: args.production.unwrap_or(false),
            force_bootloader_upgrade: args.force_bootloader_upgrade.unwrap_or(false),
            bootloader_devel: args.bootloader_devel.unwrap_or(false),
            unsafe_fw: args.unsafe_fw.unwrap_or(false),
            frozen: args.frozen.unwrap_or(false),
            source_lines: args.source_lines.unwrap_or(args.emulator),
            pyopt,
            mem_perf: args.mem_perf.unwrap_or(false),
            debug_link: args.debug_link.unwrap_or(!pyopt),
            n4w1: args.n4w1.unwrap_or(false),
            disable_animation: args.disable_animation.unwrap_or(false),
            perf_overlay: args.perf_overlay.unwrap_or(false),
            benchmark: args.benchmark.unwrap_or(false),
            log_stack_usage: args.log_stack_usage.unwrap_or(false),
            block_on_vcp: args.block_on_vcp.unwrap_or(false),
            asan: args.asan.unwrap_or(false),
            apps: args.apps.unwrap_or(false),
            disable_optiga: args.disable_optiga.unwrap_or(false),
            board: args.board.clone(),
            disable_tropic: args.disable_tropic.unwrap_or(false),
            storage_insecure_testing_mode: args.storage_insecure_testing_mode.unwrap_or(false),
            emit_memory_analysis: args.emit_memory_analysis.unwrap_or(false),
            timings: args.timings,
            verbose: args.verbose,
        }
    }

    /// Determines the Cargo profile to use
    pub fn profile_name(&self) -> &'static str {
        if self.debug {
            if self.emulator { "dev" } else { "debug-opt" }
        } else {
            "release"
        }
    }
}

#[derive(Args, Debug)]
pub struct TestArgs {
    /// Package to test
    pub packages: Vec<String>,
}

#[derive(Args, Debug)]
pub struct FlashArgs {
    pub project: Project,

    /// Target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,
}

#[derive(ValueEnum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlashSection {
    All,
    Boardloader,
    Bootloader,
    Firmware,
    Storage,
}

#[derive(Args, Debug)]
pub struct FlashEraseArgs {
    /// Flash section to erase (default All)
    #[arg(default_value = "all")]
    pub section: FlashSection,

    /// Target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,
}

#[derive(Args, Debug)]
pub struct ResetArgs {
    /// Target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,
}

#[derive(Args, Debug)]
pub struct UploadArgs {
    pub project: Project,

    /// Build target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,
}

#[derive(Args, Debug)]
pub struct CombineArgs {
    pub project: Project,

    /// Target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,
}
