use std::path::PathBuf;

use anyhow::{Result, anyhow};
use clap::{Args, Parser, Subcommand, ValueEnum};
use serde::Deserialize;

pub use crate::model::Model;
use crate::options::BuildOptions;
use crate::pq::{BootloaderSource, Variant};

#[derive(ValueEnum, Debug, Clone, Copy, Default, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Project {
    Bootloader,
    Boardloader,
    #[value(name = "bootloader_ci")]
    BootloaderCi,
    #[default]
    Firmware,
    Prodtest,
    Kernel,
    Secmon,
}

impl Project {
    /// The Rust package name used for cargo commands
    pub fn package_name(self) -> &'static str {
        match self {
            Project::Bootloader => "bootloader",
            Project::Boardloader => "boardloader",
            Project::BootloaderCi => "bootloader_ci",
            Project::Firmware => "firmware",
            Project::Prodtest => "prodtest",
            Project::Kernel => "kernel",
            Project::Secmon => "secmon",
        }
    }

    /// The linker binary type used by `build_and_link()`. This determines
    /// the `.map` filename generated by the linker.
    pub fn binary_name(self) -> &'static str {
        match self {
            Project::Bootloader => "bootloader",
            Project::BootloaderCi => "bootloader_ci",
            Project::Boardloader => "boardloader",
            Project::Firmware => "firmware",
            Project::Prodtest => "prodtest",
            Project::Kernel => "kernel",
            Project::Secmon => "secmon",
        }
    }

    /// The artifact name used for collected build outputs.
    /// Appends `-emu` for emulator builds.
    pub fn artifact_name(self, emulator: bool) -> String {
        let base = self.binary_name();
        if emulator {
            format!("{base}-emu")
        } else {
            base.to_string()
        }
    }

    /// Get symbol from memory.ld used as start address for flashing
    pub fn flash_start_symbol(self) -> Result<&'static str> {
        let symbol = match self {
            Project::Boardloader => "BOARDLOADER_START",
            Project::Bootloader | Project::BootloaderCi => "BOOTLOADER_START",
            Project::Firmware | Project::Prodtest => "FIRMWARE_START",
            _ => return Err(anyhow!("Flashing {:?} is not supported", self)),
        };
        Ok(symbol)
    }

    /// Returns the next project in the dependency chain,
    /// (e.g. Firmware -> Kernel -> Secmon)
    pub fn dependency(self, model: Model) -> Result<Option<Project>> {
        match self {
            Project::Firmware => Ok(Some(Project::Kernel)),
            Project::Kernel => {
                let has_secmon = model.config()?.secmon;
                Ok(if has_secmon {
                    Some(Project::Secmon)
                } else {
                    None
                })
            }
            _ => Ok(None),
        }
    }

    /// Returns whether the project can be flashed to a device
    /// using the `flash` subcommand.
    pub fn flashable(self) -> bool {
        self.flash_start_symbol().is_ok()
    }

    /// Returns whether the project can be uploaded to a device
    /// using the `upload` subcommand.
    pub fn uploadable(self) -> bool {
        matches!(self, Project::Firmware | Project::Prodtest)
    }
}

#[derive(ValueEnum, Debug, Clone, Copy, Default, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ConsoleType {
    /// No debug console
    #[default]
    None,
    Vcp,
    Swo,
    SystemView,
}

#[derive(Parser, Debug)]
#[command(name = "xtask")]
#[command(about = "Trezor workspace automation tasks")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Cmd,
}

#[derive(Subcommand, Debug)]
pub enum Cmd {
    /// Build a project with the specified configuration
    Build(BuildArgs),
    /// Run clippy command with the specified configuration
    Clippy(BuildArgs),
    /// Run check command with the specified configuration
    Check(BuildArgs),
    /// Run tests of specified package
    Test(TestArgs),
    /// Clean build artifacts
    Clean,
    /// Format code with rustfmt
    Fmt,
    /// Flash firmware to device using OpenOCD
    Flash(FlashArgs),
    /// Erase flash or part of it using OpenOCD
    FlashErase(FlashEraseArgs),
    /// Reset the connected device using OpenOCD
    Reset(ResetArgs),
    /// Upload firmware to device
    Upload(UploadArgs),
    /// Combine multiple firmware projects into a single binary for flashing
    Combine(CombineArgs),
    /// Build a complete pq_secure release: every variant of every tree model
    Release(ReleaseArgs),
    /// Print current version of specified project
    PrintVersion(PrintVersionArgs),
}

#[derive(Args, Debug, Clone)]
#[command(override_usage = "xtask build <PROJECT> --model <MODEL> [OPTIONS]")]
pub struct BuildArgs {
    pub project: Project,

    /// Build target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,

    /// Use emulator build
    #[arg(long, short = 'e')]
    pub emulator: bool,

    /// Build preset
    #[arg(long, short = 'p')]
    pub preset: Option<String>,

    /// Which existing bootloader binary a pq_secure release folds its
    /// firmware_root into; the bootloader is never built implicitly
    #[arg(long, value_name = "SOURCE", default_value = "auto")]
    pub bootloader: BootloaderSource,

    #[command(flatten)]
    pub options: BuildOptions,
}

#[derive(Args, Debug)]
pub struct ReleaseArgs {
    /// Build preset
    #[arg(long, short = 'p')]
    pub preset: Option<String>,

    /// Which existing bootloader binary a pq_secure release folds its
    /// firmware_root into; the bootloader is never built implicitly
    #[arg(long, value_name = "SOURCE", default_value = "auto")]
    pub bootloader: BootloaderSource,

    /// Commit the cut release under models/ as the presigned reference set
    /// (bundle, signed bootloaders, secmon pair, signed nRF image)
    #[arg(long)]
    pub promote: bool,

    /// Key slots that sign this release, as a bitmask (e.g. 0x03 for slots 0
    /// and 1); authenticated, so fixed at prepare time
    #[arg(long, value_name = "MASK", value_parser = parse_sigmask)]
    pub sigmask: Option<u8>,

    #[command(flatten)]
    pub options: BuildOptions,
}

/// Parses `0x03`, `0b11` or `3`; checked here so a bad mask does not cost a
/// full build. The signer checks again.
fn parse_sigmask(s: &str) -> Result<u8, String> {
    /// Must match BOOT_HEADER_SIGNATURE_COUNT.
    const SIGNATURE_COUNT: u32 = 2;
    /// _Static_assert(ARRAY_LENGTH(BOARDLOADER_PQ_KEYS) <= 3)
    const MAX_KEY_SLOTS: u32 = 3;

    let t = s.trim();
    let (digits, radix) = match t.get(..2) {
        Some("0x") | Some("0X") => (&t[2..], 16),
        Some("0b") | Some("0B") => (&t[2..], 2),
        _ => (t, 10),
    };
    let mask = u8::from_str_radix(digits, radix)
        .map_err(|e| format!("invalid sigmask `{s}`: {e} (expected e.g. 0x03, 0b11 or 3)"))?;

    if mask.count_ones() != SIGNATURE_COUNT {
        return Err(format!(
            "sigmask 0x{mask:02x} names {} key slot(s), but the boot header carries \
             exactly {SIGNATURE_COUNT} signatures -- name exactly {SIGNATURE_COUNT}",
            mask.count_ones()
        ));
    }
    if mask.leading_zeros() < u8::BITS - MAX_KEY_SLOTS {
        return Err(format!(
            "sigmask 0x{mask:02x} names a slot above {}, but only {MAX_KEY_SLOTS} \
             founder key slots exist (0..{})",
            MAX_KEY_SLOTS - 1,
            MAX_KEY_SLOTS - 1
        ));
    }
    Ok(mask)
}

#[derive(Args, Debug)]
pub struct TestArgs {
    /// Package to test
    pub packages: Vec<String>,
    /// Run tests under MIRI
    #[arg(long)]
    pub miri: bool,
}

#[derive(Args, Debug)]
pub struct FlashArgs {
    pub project: Project,

    /// Target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,

    /// Binary to flash, instead of this build's artifact. The destination
    /// address still comes from the project + the model's memory.ld, so this
    /// only replaces WHAT is written, not WHERE.
    #[arg(long, short = 'f', value_name = "FILE")]
    pub file: Option<PathBuf>,

    /// Which variant of a pq_secure release to flash; on `flash bootloader`,
    /// which variant to provision for (default: bare)
    #[arg(long, value_name = "VARIANT")]
    pub variant: Option<Variant>,

    /// Flash the combined image built by `xtask combine`, which puts a blank
    /// device into a working state. With `--file`, flashes that file instead
    #[arg(long)]
    pub combined: bool,
}

#[derive(ValueEnum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlashSection {
    All,
    Boardloader,
    Bootloader,
    Firmware,
    Storage,
}

#[derive(Args, Debug)]
pub struct FlashEraseArgs {
    /// Flash section to erase (default All)
    #[arg(default_value = "all")]
    pub section: FlashSection,

    /// Target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,
}

#[derive(Args, Debug)]
pub struct ResetArgs {
    /// Target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,
}

#[derive(Args, Debug)]
pub struct UploadArgs {
    pub project: Project,

    /// Build target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,

    /// Which variant of a pq_secure release to install; unset lets trezorctl
    /// pick between firmware variants
    #[arg(long, value_name = "VARIANT")]
    pub variant: Option<Variant>,
}

#[derive(Args, Debug)]
pub struct CombineArgs {
    pub project: Project,

    /// Target model
    #[arg(long, short = 'm', ignore_case = true)]
    pub model: Model,

    /// Which variant of a pq_secure release to combine; on `combine
    /// bootloader`, which variant to provision for (default: bare)
    #[arg(long, value_name = "VARIANT")]
    pub variant: Option<Variant>,
}

#[derive(Args, Debug)]
#[command(hide = true)] // Should probably go under some kind of misc subcommand.
pub struct PrintVersionArgs {
    pub project: Project,
}
