#pragma once

// OTP blocks allocation
#define FLASH_OTP_BLOCK_BATCH 0
#define FLASH_OTP_BLOCK_BOOTLOADER_VERSION 1
#define FLASH_OTP_BLOCK_VENDOR_HEADER_LOCK 2
#define FLASH_OTP_BLOCK_RANDOMNESS 3
#define FLASH_OTP_BLOCK_DEVICE_VARIANT 4
#define FLASH_OTP_BLOCK_FIRMWARE_VERSION 5
#define FLASH_OTP_BLOCK_DEVICE_SN 6
#define FLASH_OTP_BLOCK_DEVICE_VARIANT_REWORK 7
#define FLASH_OTP_BLOCK_MASTER_KEY 8
#define FLASH_OTP_BLOCK_MANUFACTURING_LOCK 9
