
# cargo-vet audits file

[[audits.cty]]
who = "matejcik <ja@matejcik.cz>"
criteria = "safe-to-deploy"
version = "0.2.2"

[[audits.stable_deref_trait]]
who = "matejcik <ja@matejcik.cz>"
criteria = "safe-to-deploy"
version = "1.2.1"
notes = "Reviewed at 1.2.0; 1.2.1 diff treated as equivalent."

[[audits.trezor-noise-protocol]]
who = "Martin Milata <martin@martinmilata.cz>"
criteria = "safe-to-deploy"
version = "0.2.1"
notes = "I am the maintainer of the crate, which is a fork based on noise-protocol-0.2.0. I am not a cryptography expert. The original crate has no unsafe code, nor filesystem or network access. It closely follows the structure of the Noise Protocol Framework specification."

[[audits.ufmt-write]]
who = "matejcik <ja@matejcik.cz>"
criteria = "safe-to-deploy"
version = "0.1.0"

[[audits.zeroize]]
who = ["matejcik <ja@matejcik.cz>", "Martin Milata <martin@martinmilata.cz>"]
criteria = "safe-to-deploy"
version = "1.8.2"

[[audits.zeroize_derive]]
who = "Martin Milata <martin@martinmilata.cz>"
criteria = "safe-to-deploy"
delta = "1.4.2 -> 1.4.3"
notes = "There are no semantic changes, only formatting and metadata."

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-27"
end = "2027-05-30"
