# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This is a Kconfig fragment which can be used to enable debug-related options
# in the application. See the README for more details.

CONFIG_NRF_APPROTECT_LOCK=y

# Declared to the STM; pairs with mcuboot_prod.conf CONFIG_BOOT_PRODUCTION_KEY.
CONFIG_TREZOR_KEY_SET_PRODUCTION=y
