header = "D002/boards/stm32u5g9j-dk.h"

[display]
driver = "io/display_ltdc_dsi"
panel = "io/display_panel_stm32u5a9j_dk"

[backlight]
driver = "io/backlight_pin"

[touch]
driver = "io/touch_sitronix"
