#ifndef STM32U5A9J_DK_H_
#define STM32U5A9J_DK_H_

#define VDD_1V8 1

#define DISPLAY_COLOR_MODE DMA2D_OUTPUT_ARGB8888
#define DISPLAY_PANEL_STM32U5A9J_DK
// #define DISPLAY_GFXMMU 1
#define DISPLAY_RESET_PIN GPIO_PIN_5
#define DISPLAY_RESET_PORT GPIOD
#define DISPLAY_RESET_CLK_ENA __HAL_RCC_GPIOD_CLK_ENABLE

#define BACKLIGHT_PIN_PIN GPIO_PIN_6
#define BACKLIGHT_PIN_PORT GPIOI
#define BACKLIGHT_PIN_CLK_ENABLE() __HAL_RCC_GPIOI_CLK_ENABLE()

// DISPLAY      : DISC2 && MCU
// BUSY (OUT)   : PB11 (CN9 pin 24, IN/SPI2_RDY)
// RES  (IN)    : PD0 (CN10 pin 35, OUT)
// D/C  (IN)    : PD9 (CN10 pin 11, OUT)
// CS   (IN)    : PB12 (CN10 pin 17, SPI2 NSS)
// SCK  (IN)    : PB13 (CN10 pin 15, SPI2 SCK)
// SDI  (IN/OUT): PD4 (CN10 pin 13, SPI2 MOSI)
// GND          : GND (CN10 pin 8)
// 3.3V         : 3.3V (CN9 pin 7)

// BUSY: Electronic paper busy signal. When the electronic paper screen is
// refreshed, BUSY pin sends a busy signal to MCU, at this time, MCU cannot read
// or write the electronic paper drive IC; When the electronic paper is
// refreshed, BUSY pin sends the idle status signal, and MCU can read and write
// the electronic paper drive IC. Busy state of BUSY pin is low level, idle
// state is high level.
// RES: Electronic paper reset signal, valid at low level.
// D/C: Data/command read/write selection, high level is data, low level is
// command.
// CS： Chip selection, active at low level.
// SCL： SPI serial communication clock signal line.
// SDA ：SPI serial communication data signal line. It's I/O from display side!!
#define DISPLAY_EP_BUSY_PIN GPIO_PIN_11
#define DISPLAY_EP_BUSY_PORT GPIOB
#define DISPLAY_EP_BUSY_CLK_ENA __HAL_RCC_GPIOB_CLK_ENABLE

#define DISPLAY_EP_RESET_PIN GPIO_PIN_0
#define DISPLAY_EP_RESET_PORT GPIOD
#define DISPLAY_EP_RESET_CLK_ENA __HAL_RCC_GPIOD_CLK_ENABLE

#define DISPLAY_EP_DC_PIN GPIO_PIN_9
#define DISPLAY_EP_DC_PORT GPIOD
#define DISPLAY_EP_DC_CLK_ENA __HAL_RCC_GPIOD_CLK_ENABLE

#define DISPLAY_EP_SPI_INSTANCE SPI2
#define DISPLAY_EP_SPI_PIN_AF GPIO_AF5_SPI2
#define DISPLAY_EP_SPI_CLK_CFG __HAL_RCC_SPI2_CONFIG
#define DISPLAY_EP_SPI_CLK_SRC RCC_SPI2CLKSOURCE_PCLK1
#define DISPLAY_EP_SPI_CLK_EN __HAL_RCC_SPI2_CLK_ENABLE
#define DISPLAY_EP_SPI_CLK_DIS __HAL_RCC_SPI2_CLK_DISABLE
#define DISPLAY_EP_SPI_FORCE_RESET __HAL_RCC_SPI2_FORCE_RESET
#define DISPLAY_EP_SPI_RELEASE_RESET __HAL_RCC_SPI2_RELEASE_RESET
#define DISPLAY_EP_SPI_MISO_PORT GPIOD // MISO not used
#define DISPLAY_EP_SPI_MISO_PIN GPIO_PIN_3 // MISO not used
#define DISPLAY_EP_SPI_MISO_CLK_EN __HAL_RCC_GPIOD_CLK_ENABLE // MISO not used
#define DISPLAY_EP_SPI_MOSI_PORT GPIOD
#define DISPLAY_EP_SPI_MOSI_PIN GPIO_PIN_4
#define DISPLAY_EP_SPI_MOSI_CLK_EN __HAL_RCC_GPIOD_CLK_ENABLE
#define DISPLAY_EP_SPI_SCK_PORT GPIOB
#define DISPLAY_EP_SPI_SCK_PIN GPIO_PIN_13
#define DISPLAY_EP_SPI_SCK_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
#define DISPLAY_EP_SPI_NSS_PORT GPIOB
#define DISPLAY_EP_SPI_NSS_PIN GPIO_PIN_12
#define DISPLAY_EP_SPI_NSS_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE

#define I2C_COUNT 1
#define I2C_INSTANCE_0 I2C5
#define I2C_INSTANCE_0_CLK_EN __HAL_RCC_I2C5_CLK_ENABLE
#define I2C_INSTANCE_0_CLK_DIS __HAL_RCC_I2C5_CLK_DISABLE
#define I2C_INSTANCE_0_PIN_AF GPIO_AF2_I2C5
#define I2C_INSTANCE_0_SDA_PORT GPIOH
#define I2C_INSTANCE_0_SDA_PIN GPIO_PIN_4
#define I2C_INSTANCE_0_SDA_CLK_EN __HAL_RCC_GPIOH_CLK_ENABLE
#define I2C_INSTANCE_0_SCL_PORT GPIOH
#define I2C_INSTANCE_0_SCL_PIN GPIO_PIN_5
#define I2C_INSTANCE_0_SCL_CLK_EN __HAL_RCC_GPIOH_CLK_ENABLE
#define I2C_INSTANCE_0_RESET_REG &RCC->APB1RSTR2
#define I2C_INSTANCE_0_RESET_BIT RCC_APB1RSTR2_I2C5RST
#define I2C_INSTANCE_0_EV_IRQHandler I2C5_EV_IRQHandler
#define I2C_INSTANCE_0_ER_IRQHandler I2C5_ER_IRQHandler
#define I2C_INSTANCE_0_EV_IRQn I2C5_EV_IRQn
#define I2C_INSTANCE_0_ER_IRQn I2C5_ER_IRQn
#define I2C_INSTANCE_0_GUARD_TIME 0

#define TOUCH_I2C_INSTANCE 0

#endif  // STM32U5A9J_DK_H_
