from micropython import const

BASE_ADDRESS_KEY_KEY = const(0)
BASE_ADDRESS_SCRIPT_KEY = const(1)
BASE_ADDRESS_KEY_SCRIPT = const(2)
BASE_ADDRESS_SCRIPT_SCRIPT = const(3)
POINTER_ADDRESS_KEY = const(4)
POINTER_ADDRESS_SCRIPT = const(5)
ENTERPRISE_ADDRESS_KEY = const(6)
ENTERPRISE_ADDRESS_SCRIPT = const(7)
BOOTSTRAP_ADDRESS = const(8)
