#!/bin/bash
set -e

rm -f ../src/trezor/messages/[A-Z]*.py
../vendor/trezor-common/protob/pb2py \
    --no-init-py \
    -o ../src/trezor/messages \
    ../vendor/trezor-common/protob/messages.proto \
    ../vendor/trezor-common/protob/messages-bitcoin.proto \
    ../vendor/trezor-common/protob/messages-cardano.proto \
    ../vendor/trezor-common/protob/messages-common.proto \
    ../vendor/trezor-common/protob/messages-crypto.proto \
    ../vendor/trezor-common/protob/messages-debug.proto \
    ../vendor/trezor-common/protob/messages-eos.proto \
    ../vendor/trezor-common/protob/messages-ethereum.proto \
    ../vendor/trezor-common/protob/messages-lisk.proto \
    ../vendor/trezor-common/protob/messages-management.proto \
    ../vendor/trezor-common/protob/messages-monero.proto \
    ../vendor/trezor-common/protob/messages-nem.proto \
    ../vendor/trezor-common/protob/messages-ripple.proto \
    ../vendor/trezor-common/protob/messages-stellar.proto \
    ../vendor/trezor-common/protob/messages-tezos.proto
