#!/usr/bin/env python3
from __future__ import annotations

import datetime
import io
from pathlib import Path

import click


@click.command()
@click.argument(
    "outfile",
    type=click.Path(dir_okay=False, writable=True, path_type=Path),
    required=False,
)
@click.option(
    "--bin",
    "-b",
    type=(click.Path(exists=True, dir_okay=False, readable=True, path_type=Path), str),
    multiple=True,
)
def main(
        bin: List[Tuple[Path, str]],
        outfile: Path | None,

) -> None:
    if outfile is None:
        today = datetime.date.today().strftime(r"%Y-%m-%d")
        outfile = Path(f"combined-{today}.bin")

    offset = int(bin[0][1], 0)
    out_bytes = io.BytesIO()

    for b in bin:
        # zero-pad until next section:
        offset += out_bytes.write(b"\x00" * (int(b[1], 0) - offset))
        assert offset == int(b[1], 0)

        # write binary
        offset += out_bytes.write(b[0].read_bytes())

    # write out contents
    click.echo(f"Writing {outfile} ({offset - int(bin[0][1], 0)} bytes)")
    outfile.write_bytes(out_bytes.getvalue())


if __name__ == "__main__":
    main()
