#!/usr/bin/env python3

"""Generate HSM key files from JSON source.

Reads common/hsm_keys.json and generates:
  - core/embed/projects/prodtest/cmd/hsm_keys.h
  - python/src/trezorlib/_root_keys.py
"""

import json
import subprocess
from pathlib import Path

import click

ROOT = Path(__file__).resolve().parent.parent.parent
JSON_SOURCE = ROOT / "common" / "hsm_keys.json"
HSM_KEYS_DEST = ROOT / "core" / "embed" / "projects" / "prodtest" / "cmd" / "hsm_keys.h"
ROOT_KEYS_DEST = ROOT / "python" / "src" / "trezorlib" / "_root_keys.py"


def c_bytes(hex_str: str) -> str:
    return (
        "{"
        + ", ".join(f"0x{hex_str[i:i + 2]}" for i in range(0, len(hex_str), 2))
        + "}"
    )


def generate_hsm_keys_h(data: dict) -> str:
    out = (
        "#pragma once\n\n"
        "// Auto-generated by core/tools/generate_hsm_keys.py\n"
        "// Source: common/hsm_keys.json\n"
    )

    for name, hex_val in data["shared"].items():
        out += f"\n#define {name} {c_bytes(hex_val)}\n"

    for model, keys in data["models"].items():
        out += f"\n#ifdef TREZOR_MODEL_{model}\n"
        for name, hex_val in keys.items():
            out += f"\n#define {name} {c_bytes(hex_val)}\n"
        out += f"\n#endif // TREZOR_MODEL_{model}\n"

    result = subprocess.run(
        ["clang-format"], input=out, capture_output=True, text=True, check=True
    )
    return result.stdout


def generate_root_keys_py(data: dict) -> str:
    out = """\
# This file is part of the Trezor project.
#
# Copyright (C) SatoshiLabs and contributors
#
# This library is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License version 3
# as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the License along with this library.
# If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.

# Auto-generated by core/tools/generate_hsm_keys.py
# Source: common/hsm_keys.json

# fmt: off
"""

    for model, keys in data["models"].items():
        for name, hex_val in keys.items():
            if name.startswith("HSM_"):
                continue
            out += f'\n{model}_{name}_HEX = "{hex_val}"\n'

    return out


def check_file(dest: Path, expected: str) -> None:
    if not dest.exists():
        raise click.ClickException(f"{dest} is missing")
    if dest.read_text() != expected:
        raise click.ClickException(f"{dest} is out of date")


@click.command()
@click.option("--check", is_flag=True)
def generate(check: bool) -> None:
    """Generate HSM key files from the JSON source."""
    with open(JSON_SOURCE) as f:
        data = json.load(f)

    hsm = generate_hsm_keys_h(data)
    py = generate_root_keys_py(data)

    if check:
        check_file(HSM_KEYS_DEST, hsm)
        check_file(ROOT_KEYS_DEST, py)
        print("All files are up to date.")
    else:
        HSM_KEYS_DEST.write_text(hsm)
        ROOT_KEYS_DEST.write_text(py)
        print(f"Generated {HSM_KEYS_DEST}")
        print(f"Generated {ROOT_KEYS_DEST}")


if __name__ == "__main__":
    generate()
