#!/usr/bin/env python3

import json
import os
from pathlib import Path

import click
import yaml
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    NoEncryption,
    PrivateFormat,
    PublicFormat,
    load_pem_private_key,
)

HERE = Path(__file__).parent
ROOT = HERE.parent.parent.resolve()
CONFIG_DIR = ROOT / "tests" / "tropic_model"
DEST_PATH = CONFIG_DIR / "config.yml"
CFG_SPEC_PATH = (
    ROOT / "core" / "embed" / "sec" / "tropic" / "config" / "tropic_configs.json"
)

BASE_CONFIG = CONFIG_DIR / "base_config.yml"
CERT_CHAIN_DIR = CONFIG_DIR / "tropic_cert_chain"
CERT_STORE_PATH = CERT_CHAIN_DIR / "cert_store.der"

HEADER = f"""# This file is auto-generated by `{Path(__file__).relative_to(ROOT)}`.
# Do not edit this file directly. Instead, run `make gen` or
# `make tropic_config` in the root directory.\n
"""


def get_tropic_configuration(path: Path) -> dict:
    with open(path, "r") as f:
        all_config_versions = json.load(f)

    config = {}
    for type_of_config in ["reversible_configurations", "irreversible_configurations"]:
        short_name = (
            "r_config" if type_of_config == "reversible_configurations" else "i_config"
        )
        for config_version in all_config_versions[type_of_config]:
            if config_version["version"] == 0:  # 0 is the default version
                config[short_name] = config_version["config"]
                break

    numbers = {"i_config": {}, "r_config": {}}
    for category in config["i_config"]:
        number = 0xFFFFFFFF
        if "uap" not in category:
            for details in config["i_config"][category]["setting"].values():
                if not details["value"]:
                    number &= ~(1 << details["bit"])
            numbers["i_config"][category] = number
        else:
            for i in range(4):
                for details in config["i_config"][category]["setting"][
                    f"pairing_key_{i}"
                ].values():
                    if not details["value"]:
                        number &= ~(1 << details["bit"])
            numbers["i_config"][category] = number

    for category in config["r_config"]:
        number = 0
        if "uap" not in category:
            for details in config["r_config"][category]["setting"].values():
                if details["value"]:
                    number |= 1 << details["bit"]
            numbers["r_config"][category] = number
        else:
            for i in range(4):
                for details in config["r_config"][category]["setting"][
                    f"pairing_key_{i}"
                ].values():
                    if details["value"]:
                        number |= 1 << details["bit"]
            numbers["r_config"][category] = number
    return numbers


@click.command()
@click.option("--check", is_flag=True)
def generate_config(check: bool) -> None:
    device_private_key = load_pem_private_key(
        (CERT_CHAIN_DIR / "l3.key").read_bytes(), None
    )
    cert_store = CERT_STORE_PATH.read_bytes()

    chip_id = bytes.fromhex("0" * 192 + "19071f0a04" + "0" * 54)
    tropic_cfg = get_tropic_configuration(CFG_SPEC_PATH)

    config_dict = {
        "s_t_priv": device_private_key.private_bytes(
            Encoding.Raw, PrivateFormat.Raw, NoEncryption()
        ),
        "s_t_pub": device_private_key.public_key().public_bytes(
            Encoding.Raw, PublicFormat.Raw
        ),
        "x509_certificate": cert_store,
        "debug_random_value": b"\x00\xc0\xff\xee",
        "chip_id": chip_id,
        "riscv_fw_version": "1.0.0",  # Version of the RISCV Firmware (also know as Application FW) used in TS7 devices
        "spect_fw_version": "1.0.0",
        "r_config": tropic_cfg["r_config"],
        "i_config": tropic_cfg["i_config"],
        "i_pairing_keys": {
            0: {
                "value": bytes.fromhex(
                    "0000000000000000000000000000000000000000000000000000000000000000"
                ),
                "state": "invalid",
            },
            1: {
                "value": bytes.fromhex(
                    "ce8d3ad1ccb633ec7b70c17814a5c76ecd029685050d344745ba05870e587d59"
                ),
                "state": "written",
            },
            2: {
                "value": bytes.fromhex(
                    "842fe321a82474083737ff2b9b88a2af42442db0d8aacc6dc69e99533344b246"
                ),
                "state": "written",
            },
        },
    }

    base_config = yaml.safe_load(BASE_CONFIG.read_text())
    # r_user_data slots 3-5 (the device certificate chain used in Trezor's
    # authenticity check) come from base_config; slot 6 is generated here.
    # See https://github.com/trezor/trezor-firmware/blob/main/core/embed/sec/tropic/inc/sec/tropic.h#L31
    TROPIC_CONFIG_DISTRIBUTION_VERSION_SLOT = 6
    base_config["r_user_data"][TROPIC_CONFIG_DISTRIBUTION_VERSION_SLOT] = {
        "value": (0).to_bytes(4, "big")
    }

    overlap = config_dict.keys() & base_config.keys()
    if overlap:
        raise click.ClickException(
            f"Key collision between base_config and generated config: {overlap}"
        )
    config = HEADER + yaml.dump({**base_config, **config_dict})

    if check:
        if not DEST_PATH.exists():
            print(f"{DEST_PATH} missing")
            raise click.ClickException("Config file is missing")
        elif config != DEST_PATH.read_text():
            raise click.ClickException("Config file is out of date")
        if not CERT_STORE_PATH.exists():
            print(f"{CERT_STORE_PATH} missing")
            raise click.ClickException("Cert store file is missing")
    else:
        base_config_stat = BASE_CONFIG.stat()
        cfg_spec_stat = CFG_SPEC_PATH.stat()
        cert_store_stat = CERT_STORE_PATH.stat()
        device_key_stat = (CERT_CHAIN_DIR / "l3.key").stat()
        DEST_PATH.write_text(config)
        os.utime(
            DEST_PATH,
            ns=(
                max(
                    base_config_stat.st_atime_ns,
                    cfg_spec_stat.st_atime_ns,
                    cert_store_stat.st_atime_ns,
                    device_key_stat.st_atime_ns,
                ),
                max(
                    base_config_stat.st_mtime_ns,
                    cfg_spec_stat.st_mtime_ns,
                    cert_store_stat.st_mtime_ns,
                    device_key_stat.st_mtime_ns,
                ),
            ),
        )


if __name__ == "__main__":
    generate_config()
