[package]
name = "trezor_lib"
version = "0.0.0"
authors = ["SatoshiLabs <info@satoshilabs.com>"]
edition = "2021"
links = "trezor_lib"

[lib]
crate-type = ["rlib"]
doctest = false

[build-dependencies]
bindgen.workspace = true
xbuild.workspace = true

[dev-dependencies]
hex.workspace = true
serde_json.workspace = true

[dependencies]
cfg-if.workspace = true
cty.workspace = true
easer.workspace = true
heapless.workspace = true
log.workspace = true
minicbor.workspace = true
num-derive.workspace = true
num-traits.workspace = true
pareen.workspace = true
qrcodegen.workspace = true
spin.workspace = true
static-alloc.workspace = true
trezor-thp = { workspace = true, optional = true }
trezor-tjpgdec.workspace = true
ufmt.workspace = true
unsize.workspace = true
without-alloc.workspace = true
zeroize = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
trezor-app-sdk = { workspace = true, optional = true }

# crates in embed/ directory
crypto.workspace = true
io.workspace = true
models.workspace = true
rtl.workspace = true
sec.workspace = true
sys.workspace = true
upymod = { workspace = true, optional = true }

[features]

# --------------------------------------------------------------------------
# Selectable components
# --------------------------------------------------------------------------

app_loading = ["dep:trezor-app-sdk", "dep:rkyv"]
backlight = []
ble = []
boot_ucb = []
bootloader = []
button = []
clippy = []
crypto = []
dbg_console = []
debug = ["ui_debug", "dev_keys"]
debuglink = []
dev_keys = []
display_mono = []
display_rgb565 = ["ui_antialiasing"]
display_rgba8888 = ["ui_antialiasing"]
dma2d = []
framebuffer = []
haptic = []
hw_jpeg_decoder = []
layout_bolt = []
layout_caesar = []
layout_delizia = []
layout_eckhart = []
micropython = ["dep:upymod"]
n4w1 = []
nrf = []
optiga = []
pmic = []
power_manager = []
prodtest = []
protobuf = ["micropython"]
rgb_led = []
sbu = []
sd_card = []
secmon_layout = []
serial_number = []
smp = []
storage = []
telemetry = []
thp = ["crypto/thp", "dep:trezor-thp", "dep:zeroize"]
touch = []
touch_wakeup = []
translations = ["crypto"]
tropic = []
ui = []
ui_antialiasing = []
ui_blurring = []
ui_color_32bit = []
ui_debug = []
ui_debug_overlay = []
ui_empty_lock = []
ui_font_kerning = []
ui_image_buffer = []
ui_jpeg = []
ui_overlay = []
ui_performance_overlay = []
universal_fw = []
usb = []

# --------------------------------------------------------------------------
# Unit test configuration
# --------------------------------------------------------------------------

test = [
    "crypto/aes_gcm",
    "emulator",
    "io/button",
    "io/display_panel_t2t1",
    "io/emulator",
    "io/fancy_fatal_error",
    "io/kernel_mode",
    "io/mcu_stm32f429",
    "io/nrf",
    "io/secure_mode",
    "io/touch",
    "mcu_stm32f429",
    "models/model_t2t1",
    "sec/secret",
    "sys/dbg_console",
    "upymod/emulator",
    "upymod/layout_bolt",
    "upymod/universal_fw",

    "backlight",
    "button",
    "crypto",
    "dbg_console",
    "debug",
    "dma2d",
    "layout_bolt",
    "micropython",
    "nrf",
    "optiga",
    "protobuf",
    "smp",
    "storage",
    "thp",
    "touch",
    "translations",
    "trezor-thp?/use_std",
    "ui_blurring",
    "ui_empty_lock",
    "ui_font_kerning",
    "ui_image_buffer",
    "ui_jpeg",
    "ui_overlay",
    "ui",
    "universal_fw",
]

# --------------------------------------------------------------------------
# Automatically derived features (do not enable from outside)
# --------------------------------------------------------------------------

default = []

# TODO: should we propagate the emulator feature here? some say yes, some say no.
# For now we propagate, but this is NOT a project wide policy.
emulator = ["io/emulator", "upymod?/emulator"]
mcu_stm32f429 = ["mcu_stm32f4"]
mcu_stm32f4 = []

