#pragma once

#define VDD_1V8 1

#define BTN_LEFT_PIN GPIO_PIN_10
#define BTN_LEFT_PORT GPIOA
#define BTN_LEFT_CLK_ENA __HAL_RCC_GPIOA_CLK_ENABLE
#define BTN_RIGHT_PIN GPIO_PIN_11
#define BTN_RIGHT_PORT GPIOA
#define BTN_RIGHT_CLK_ENA __HAL_RCC_GPIOA_CLK_ENABLE

// #define OLED_DC_PORT GPIOC
// #define OLED_DC_PIN GPIO_PIN_8  // Data/Command
// #define OLED_DC_CLK_ENA __HAL_RCC_GPIOC_CLK_ENABLE
// #define OLED_CS_PORT GPIOG
// #define OLED_CS_PIN GPIO_PIN_5  // SPI Select
// #define OLED_CS_CLK_ENA __HAL_RCC_GPIOG_CLK_ENABLE
// #define OLED_RST_PORT GPIOG
// #define OLED_RST_PIN GPIO_PIN_8  // Reset display
// #define OLED_RST_CLK_ENA __HAL_RCC_GPIOG_CLK_ENABLE
//
// #define OLED_SPI SPI1
// #define OLED_SPI_AF GPIO_AF5_SPI1
// #define OLED_SPI_CLK_ENA __HAL_RCC_SPI1_CLK_ENABLE
// #define OLED_SPI_SCK_PORT GPIOG
// #define OLED_SPI_SCK_PIN GPIO_PIN_2  // SPI SCK
// #define OLED_SPI_SCK_CLK_ENA __HAL_RCC_GPIOG_CLK_ENABLE
// #define OLED_SPI_MOSI_PORT GPIOG
// #define OLED_SPI_MOSI_PIN GPIO_PIN_4  // SPI MOSI
// #define OLED_SPI_MOSI_CLK_ENA __HAL_RCC_GPIOG_CLK_ENABLE

// #define I2C_COUNT 1
// #define I2C_INSTANCE_0 I2C1
// #define I2C_INSTANCE_0_CLK_EN __HAL_RCC_I2C1_CLK_ENABLE
// #define I2C_INSTANCE_0_CLK_DIS __HAL_RCC_I2C1_CLK_DISABLE
// #define I2C_INSTANCE_0_PIN_AF GPIO_AF4_I2C1
// #define I2C_INSTANCE_0_SDA_PORT GPIOG
// #define I2C_INSTANCE_0_SDA_PIN GPIO_PIN_13
// #define I2C_INSTANCE_0_SDA_CLK_EN __HAL_RCC_GPIOG_CLK_ENABLE
// #define I2C_INSTANCE_0_SCL_PORT GPIOG
// #define I2C_INSTANCE_0_SCL_PIN GPIO_PIN_14
// #define I2C_INSTANCE_0_SCL_CLK_EN __HAL_RCC_GPIOG_CLK_ENABLE
// #define I2C_INSTANCE_0_RESET_REG &RCC->APB1RSTR1
// #define I2C_INSTANCE_0_RESET_BIT RCC_APB1RSTR1_I2C1RST
// #define I2C_INSTANCE_0_EV_IRQHandler I2C1_EV_IRQHandler
// #define I2C_INSTANCE_0_ER_IRQHandler I2C1_ER_IRQHandler
// #define I2C_INSTANCE_0_EV_IRQn I2C1_EV_IRQn
// #define I2C_INSTANCE_0_ER_IRQn I2C1_ER_IRQn
// #define I2C_INSTANCE_0_GUARD_TIME 50  // Optiga requires 50us guard time

// #define OPTIGA_I2C_INSTANCE 0
// #define OPTIGA_RST_PORT GPIOE
// #define OPTIGA_RST_PIN GPIO_PIN_13
// #define OPTIGA_RST_CLK_EN __HAL_RCC_GPIOE_CLK_ENABLE
// #define OPTIGA_PWR_PORT GPIOF
// #define OPTIGA_PWR_PIN GPIO_PIN_13
// #define OPTIGA_PWR_CLK_EN __HAL_RCC_GPIOF_CLK_ENABLE

// #define SBU_1_PIN GPIO_PIN_2
// #define SBU_1_PORT GPIOA
// #define SBU_1_CLK_ENA __HAL_RCC_GPIOA_CLK_ENABLE
// #define SBU_2_PIN GPIO_PIN_3
// #define SBU_2_PORT GPIOA
// #define SBU_2_CLK_ENA __HAL_RCC_GPIOA_CLK_ENABLE

#define HW_REVISION_PUPD GPIO_PULLUP
#define HW_REVISION_0_PIN GPIO_PIN_0
#define HW_REVISION_0_PORT GPIOF
#define HW_REVISION_0_CLOCK_ENABLE() __HAL_RCC_GPIOF_CLK_ENABLE()
#define HW_REVISION_1_PIN GPIO_PIN_1
#define HW_REVISION_1_PORT GPIOF
#define HW_REVISION_1_CLOCK_ENABLE() __HAL_RCC_GPIOF_CLK_ENABLE()
#define HW_REVISION_2_PIN GPIO_PIN_2
#define HW_REVISION_2_PORT GPIOF
#define HW_REVISION_2_CLOCK_ENABLE() __HAL_RCC_GPIOF_CLK_ENABLE()
#define HW_REVISION_3_PIN GPIO_PIN_3
#define HW_REVISION_3_PORT GPIOF
#define HW_REVISION_3_CLOCK_ENABLE() __HAL_RCC_GPIOF_CLK_ENABLE()

#define NRF_SPI_INSTANCE SPI1
#define NRF_SPI_CLK_EN __HAL_RCC_SPI1_CLK_ENABLE
#define NRF_SPI_CLK_DIS __HAL_RCC_SPI1_CLK_DISABLE
#define NRF_SPI_FORCE_RESET __HAL_RCC_SPI1_FORCE_RESET
#define NRF_SPI_RELEASE_RESET __HAL_RCC_SPI1_RELEASE_RESET
#define NRF_SPI_PIN_AF GPIO_AF5_SPI1
#define NRF_SPI_DMA_RX_REQUEST GPDMA1_REQUEST_SPI1_RX
#define NRF_SPI_DMA_TX_REQUEST GPDMA1_REQUEST_SPI1_TX
#define NRF_SPI_SCK_PORT GPIOA
#define NRF_SPI_SCK_PIN GPIO_PIN_5
#define NRF_SPI_SCK_CLK_EN __HAL_RCC_GPIOA_CLK_ENABLE
#define NRF_SPI_NSS_PORT GPIOA
#define NRF_SPI_NSS_PIN GPIO_PIN_4
#define NRF_SPI_NSS_CLK_EN __HAL_RCC_GPIOA_CLK_ENABLE
#define NRF_SPI_MISO_PORT GPIOA
#define NRF_SPI_MISO_PIN GPIO_PIN_6
#define NRF_SPI_MISO_CLK_EN __HAL_RCC_GPIOA_CLK_ENABLE
#define NRF_SPI_MOSI_PORT GPIOA
#define NRF_SPI_MOSI_PIN GPIO_PIN_7
#define NRF_SPI_MOSI_CLK_EN __HAL_RCC_GPIOA_CLK_ENABLE

#define NRF_UART_INSTANCE USART1
#define NRF_UART_CLK_EN __HAL_RCC_USART1_CLK_ENABLE
#define NRF_UART_CLK_DIS __HAL_RCC_USART1_CLK_DISABLE
#define NRF_UART_FORCE_RESET __HAL_RCC_USART1_FORCE_RESET
#define NRF_UART_RELEASE_RESET __HAL_RCC_USART1_RELEASE_RESET
#define NRF_UART_PIN_AF GPIO_AF7_USART1
#define NRF_UART_TX_PORT GPIOA
#define NRF_UART_TX_PIN GPIO_PIN_9
#define NRF_UART_TX_CLK_EN __HAL_RCC_GPIOA_CLK_ENABLE
#define NRF_UART_RX_PORT GPIOA
#define NRF_UART_RX_PIN GPIO_PIN_10
#define NRF_UART_RX_CLK_EN __HAL_RCC_GPIOA_CLK_ENABLE
#define NRF_UART_RTS_PORT GPIOB
#define NRF_UART_RTS_PIN GPIO_PIN_3
#define NRF_UART_RTS_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
#define NRF_UART_CTS_PORT GPIOB
#define NRF_UART_CTS_PIN GPIO_PIN_4
#define NRF_UART_CTS_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE

#define NRF_IN_RESERVED_PIN GPIO_PIN_10
#define NRF_IN_RESERVED_PORT GPIOC
#define NRF_IN_RESERVED_CLK_ENA __HAL_RCC_GPIOC_CLK_ENABLE
#define NRF_OUT_RESET_PIN GPIO_PIN_11
#define NRF_OUT_RESET_PORT GPIOC
#define NRF_OUT_RESET_CLK_ENA __HAL_RCC_GPIOC_CLK_ENABLE
#define NRF_OUT_STAY_IN_BLD_PIN GPIO_PIN_13
#define NRF_OUT_STAY_IN_BLD_PORT GPIOC
#define NRF_OUT_STAY_IN_BLD_CLK_ENA __HAL_RCC_GPIOC_CLK_ENABLE
#define NRF_OUT_SPI_READY_PIN GPIO_PIN_2
#define NRF_OUT_SPI_READY_PORT GPIOD
#define NRF_OUT_SPI_READY_CLK_ENA __HAL_RCC_GPIOD_CLK_ENABLE
#define NRF_IN_SPI_REQUEST_PIN GPIO_PIN_12
#define NRF_IN_SPI_REQUEST_PORT GPIOC
#define NRF_IN_SPI_REQUEST_CLK_ENA __HAL_RCC_GPIOC_CLK_ENABLE
#define NRF_EXTI_INTERRUPT_GPIOSEL EXTI_GPIOC
#define NRF_EXTI_INTERRUPT_LINE EXTI_LINE_12
#define NRF_EXTI_INTERRUPT_PIN GPIO_PIN_12
#define NRF_EXTI_INTERRUPT_NUM EXTI12_IRQn
#define NRF_EXTI_INTERRUPT_HANDLER EXTI12_IRQHandler
