#define VERSION_MAJOR 2
#define VERSION_MINOR 6
#define VERSION_PATCH 3
#define VERSION_BUILD 0

#define FIX_VERSION_MAJOR 2
#define FIX_VERSION_MINOR 4
#define FIX_VERSION_PATCH 0
#define FIX_VERSION_BUILD 0

#define VERSION_MONOTONIC 1
