# Automatically generated by pb2py
import protobuf as p
from micropython import const
t = p.MessageType('Address')
t.wire_type = const(30)
t.add_field(1, 'address', p.UnicodeType, flags=p.FLAG_REQUIRED)
Address = t