# Automatically generated by pb2py
from micropython import const

Other = const(1)
FeeOverThreshold = const(2)
ConfirmOutput = const(3)
ResetDevice = const(4)
ConfirmWord = const(5)
WipeDevice = const(6)
ProtectCall = const(7)
SignTx = const(8)
FirmwareCheck = const(9)
Address = const(10)
PublicKey = const(11)
MnemonicWordCount = const(12)
MnemonicInput = const(13)
PassphraseType = const(14)
