# Automatically generated by pb2py
import protobuf as p


class CosiCommit(p.MessageType):
    FIELDS = {
        1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        2: ('data', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 71
