# Automatically generated by pb2py
import protobuf as p
from micropython import const
t = p.MessageType('DebugLinkMemoryRead')
t.wire_type = const(110)
t.add_field(1, 'address', p.UVarintType)
t.add_field(2, 'length', p.UVarintType)
DebugLinkMemoryRead = t
