# Automatically generated by pb2py
from protobuf import protobuf as p
from .HDNodeType import HDNodeType
t = p.MessageType()
t.add_field(1, 'layout', p.BytesType)
t.add_field(2, 'pin', p.UnicodeType)
t.add_field(3, 'matrix', p.UnicodeType)
t.add_field(4, 'mnemonic', p.UnicodeType)
t.add_field(5, 'node', p.EmbeddedMessage(HDNodeType))
t.add_field(6, 'passphrase_protection', p.BoolType)
t.add_field(7, 'reset_word', p.UnicodeType)
t.add_field(8, 'reset_entropy', p.BytesType)
t.add_field(9, 'recovery_fake_word', p.UnicodeType)
t.add_field(10, 'recovery_word_pos', p.UVarintType)
DebugLinkState = t
TYPE = const(102)