# Automatically generated by pb2py
# fmt: off
import protobuf as p


class DebugLinkFlashErase(p.MessageType):
    MESSAGE_WIRE_TYPE = 113
    FIELDS = {
        1: ('sector', p.UVarintType, 0),
    }

    def __init__(
        self,
        sector: int = None,
    ) -> None:
        self.sector = sector
