# Automatically generated by pb2py
import protobuf as p
from micropython import const

class DebugLinkMemory(p.MessageType):
    FIELDS = {
        1: ('memory', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 111
