# Automatically generated by pb2py
import protobuf as p
from micropython import const
t = p.MessageType('ECDHSessionKey')
t.wire_type = const(62)
t.add_field(1, 'session_key', p.BytesType)
ECDHSessionKey = t
