# Automatically generated by pb2py
import protobuf as p
from micropython import const

class EthereumAddress(p.MessageType):
    FIELDS = {
        1: ('address', p.BytesType, 0), # required
    }
    MESSAGE_WIRE_TYPE = 57
