# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .HDNodeType import HDNodeType


class EthereumPublicKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 451

    def __init__(
        self,
        node: HDNodeType = None,
        xpub: str = None,
    ) -> None:
        self.node = node
        self.xpub = xpub

    @classmethod
    def get_fields(cls):
        return {
            1: ('node', HDNodeType, 0),
            2: ('xpub', p.UnicodeType, 0),
        }
