# Automatically generated by pb2py
import protobuf as p


class GetEntropy(p.MessageType):
    FIELDS = {
        1: ('size', p.UVarintType, 0),  # required
    }
    MESSAGE_WIRE_TYPE = 9

    def __init__(
        self,
        size: int = None,
        **kwargs,
    ):
        self.size = size
        p.MessageType.__init__(self, **kwargs)
