# Automatically generated by pb2py
import protobuf as p


class Initialize(p.MessageType):
    FIELDS = {
        1: ('state', p.BytesType, 0),
        2: ('skip_passphrase', p.BoolType, 0),
    }
    MESSAGE_WIRE_TYPE = 0

    def __init__(
        self,
        state: bytes = None,
        skip_passphrase: bool = None,
        **kwargs,
    ):
        self.state = state
        self.skip_passphrase = skip_passphrase
        p.MessageType.__init__(self, **kwargs)
