# Automatically generated by pb2py
import protobuf as p


class LiskVerifyMessage(p.MessageType):
    FIELDS = {
        1: ('signature', p.BytesType, 0),
        2: ('public_key', p.BytesType, 0),
        3: ('message', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 120

    def __init__(
        self,
        signature: bytes = None,
        public_key: bytes = None,
        message: bytes = None,
        **kwargs,
    ):
        self.signature = signature
        self.public_key = public_key
        self.message = message
        p.MessageType.__init__(self, **kwargs)
