# Automatically generated by pb2py
from micropython import const

Transfer = const(0)
RegisterSecondPassphrase = const(1)
RegisterDelegate = const(2)
CastVotes = const(3)
RegisterMultisignatureAccount = const(4)
CreateDapp = const(5)
TransferIntoDapp = const(6)
TransferOutOfDapp = const(7)
