# Automatically generated by pb2py
import protobuf as p


class LiskDelegateType(p.MessageType):
    FIELDS = {
        1: ('username', p.UnicodeType, 0),
    }

    def __init__(
        self,
        username: str = None,
        **kwargs,
    ):
        self.username = username
        p.MessageType.__init__(self, **kwargs)
