# Automatically generated by pb2py
import protobuf as p
t = p.MessageType('MessageSignature')
t.wire_type = 40
t.add_field(1, 'address', p.UnicodeType)
t.add_field(2, 'signature', p.BytesType)
MessageSignature = t