# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .MoneroTransferDetails import MoneroTransferDetails

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class MoneroKeyImageSyncStepRequest(p.MessageType):
    FIELDS = {
        1: ('tdis', MoneroTransferDetails, p.FLAG_REPEATED),
    }

    def __init__(
        self,
        tdis: List[MoneroTransferDetails] = None,
    ) -> None:
        self.tdis = tdis if tdis is not None else []
