# Automatically generated by pb2py
import protobuf as p
from micropython import const
from .HDNodePathType import HDNodePathType
t = p.MessageType('MultisigRedeemScriptType')
t.add_field(1, 'pubkeys', p.EmbeddedMessage(HDNodePathType), flags=p.FLAG_REPEATED)
t.add_field(2, 'signatures', p.BytesType, flags=p.FLAG_REPEATED)
t.add_field(3, 'm', p.UVarintType)
MultisigRedeemScriptType = t