# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .OntologyOntIdRegister import OntologyOntIdRegister
from .OntologyTransaction import OntologyTransaction

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class OntologySignOntIdRegister(p.MessageType):
    MESSAGE_WIRE_TYPE = 358
    FIELDS = {
        1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        2: ('transaction', OntologyTransaction, 0),
        3: ('ont_id_register', OntologyOntIdRegister, 0),
    }

    def __init__(
        self,
        address_n: List[int] = None,
        transaction: OntologyTransaction = None,
        ont_id_register: OntologyOntIdRegister = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.transaction = transaction
        self.ont_id_register = ont_id_register
