# Automatically generated by pb2py
from micropython import const

import protobuf as p

class PassphraseAck(p.MessageType):
    FIELDS = {
        1: ('passphrase', p.UnicodeType, 0), # required
    }
    MESSAGE_WIRE_TYPE = 42
