# Automatically generated by pb2py
import protobuf as p
from micropython import const

class SetU2FCounter(p.MessageType):
    FIELDS = {
        1: ('u2f_counter', p.UVarintType, 0),
    }
    MESSAGE_WIRE_TYPE = 63
