# Automatically generated by pb2py
import protobuf as p
from .TransactionType import TransactionType
from .TxInputType import TxInputType
from .TxOutputType import TxOutputType


class SimpleSignTx(p.MessageType):
    FIELDS = {
        1: ('inputs', TxInputType, p.FLAG_REPEATED),
        2: ('outputs', TxOutputType, p.FLAG_REPEATED),
        3: ('transactions', TransactionType, p.FLAG_REPEATED),
        4: ('coin_name', p.UnicodeType, 0),  # default='Bitcoin'
        5: ('version', p.UVarintType, 0),  # default=1
        6: ('lock_time', p.UVarintType, 0),  # default=0
    }
    MESSAGE_WIRE_TYPE = 16

    def __init__(
        self,
        inputs: list = None,
        outputs: list = None,
        transactions: list = None,
        coin_name: str = None,
        version: int = None,
        lock_time: int = None,
        **kwargs,
    ):
        self.inputs = [] if inputs is None else inputs
        self.outputs = [] if outputs is None else outputs
        self.transactions = [] if transactions is None else transactions
        self.coin_name = coin_name
        self.version = version
        self.lock_time = lock_time
        p.MessageType.__init__(self, **kwargs)
