# Automatically generated by pb2py
import protobuf as p


class StellarCreateAccountOp(p.MessageType):
    FIELDS = {
        1: ('source_account', p.BytesType, 0),
        2: ('new_account', p.BytesType, 0),
        3: ('starting_balance', p.Sint64Type, 0),
    }
    MESSAGE_WIRE_TYPE = 210

    def __init__(
        self,
        source_account: bytes = None,
        new_account: bytes = None,
        starting_balance: int = None,
        **kwargs,
    ):
        self.source_account = source_account
        self.new_account = new_account
        self.starting_balance = starting_balance
        p.MessageType.__init__(self, **kwargs)
