# Automatically generated by pb2py
import protobuf as p


class StellarBumpSequenceOp(p.MessageType):
    FIELDS = {
        1: ('source_account', p.BytesType, 0),
        2: ('bump_to', p.UVarintType, 0),
    }
    MESSAGE_WIRE_TYPE = 221

    def __init__(
        self,
        source_account: bytes = None,
        bump_to: int = None,
        **kwargs,
    ):
        self.source_account = source_account
        self.bump_to = bump_to
        p.MessageType.__init__(self, **kwargs)
