/*
 * nRF-specific shims, on top of the shared ones.
 *
 * Adds what nrf_image.c needs that the firmware-tree harness does not: the
 * generated vector (which carries the classic key pool the fixtures were signed
 * with), that pool presented as this "model's" MODEL_NRF_LEGACY_KEYS_*, and a real
 * Ed25519 so the classic acceptance predicate runs instead of being compiled out.
 *
 * The pool has to be visible BEFORE nrf_image.c is compiled, which is why
 * this is a header delivered with -include rather than something the harness .c
 * sets up for itself.
 */

#pragma once

#include <stdbool.h>

#include "shims.h"

/* Shimmed from sec/boot_header.h, which declares it beside nrf_image_verify_in_tree.
 * Keep in step with the real definition -- there is only meant to be one. */
#define MODEL_TREE_MAX_PROOF_NODES 32U

#include <io/nrf_image.h> /* the shared format numbers */

/* The vector comes FIRST: it carries the classic key pool, and the pool has to be
 * defined before nrf_image.c is compiled. */
#include "nrf_vector.h" /* generated by gen_nrf_vector.py */

/* Hand the device code that pool as this "model's" MODEL_NRF_LEGACY_KEYS_*, and
 * declare that an Ed25519 implementation is linked (run_nrf.sh links the monorepo's
 * -- the same one boot_header.c uses on device, which is the point: this is STM
 * code, unlike pq_sig_test.c which drives the nRF's own copy).
 *
 * Together these make nrf_image_legacy_accept_ok compile and RUN, so the classic
 * acceptance predicate is exercised against real signatures rather than stubbed
 * out. Without them the push gate's classic branch would only reach the shape
 * check. */
#define MODEL_NRF_LEGACY_KEYS_DEVEL \
  NRF_LEGACY_KEY_0, NRF_LEGACY_KEY_1, NRF_LEGACY_KEY_2
#define MODEL_NRF_LEGACY_KEYS_PRODUCTION MODEL_NRF_LEGACY_KEYS_DEVEL
#define NRF_LEGACY_ED25519_HOST

#include <ed25519-donna/ed25519.h>

/* sec keeps only the generic slot fold now; the nRF entry points are io/nrf's. */
secbool boot_header_verify_slot(const uint8_t* slot_value,
                                const merkle_proof_node_t* proof,
                                size_t proof_count,
                                const merkle_proof_node_t* trusted_model_root);
secbool nrf_image_verify_in_tree(const uint8_t* image, size_t image_len,
                           const merkle_proof_node_t* proof, size_t proof_count,
                           const merkle_proof_node_t* trusted_model_root);
secbool nrf_image_verify_for_push(const uint8_t* image, size_t image_len,
                               const merkle_proof_node_t* trusted_model_root,
                               const uint8_t* expected_slh_sig0,
                               const uint8_t* expected_slh_sig1,
                               const uint8_t* expected_ec_sig0,
                               const uint8_t* expected_ec_sig1);

#include "nrf_image_internal.h"
