header = "T3T2/boards/devkit.h"
emulator_header = "T3T2/boards/unix.h"

[display]
driver = "io/display_i8080"
panel = "io/display_panel_lx200b4501ctp03"

[backlight]
driver = "io/backlight_pwm"

[touch]
driver = "io/touch_ft6x36"
panel = "io/touch_panel_lx200b4501ctp03"

[button]

[optiga]

[tropic]

[power_manager]
pmic = "io/pmic_power_latch"
fuel_gauge = "io/fuel_gauge_mock"

[ble]

[nrf]

[nrf_auth]
