#pragma once

#define VDD_3V3 1

// ST7789 (Display Elektronik DEM240320B1) over 16-bit i8080 FMC bus.
// The module has no tearing-effect (TE) output, so no DISPLAY_TE_* defines.
#define DISPLAY_I8080_16BIT_DW 1

// Use a single framebuffer on this project (lower RAM use; there is no TE
// signal to drive smooth double-buffered swaps anyway).
#define FRAME_BUFFER_COUNT 1

#define DISPLAY_IDENTIFY 1

// Display reset (DISPL_NRST)
#define DISPLAY_RST_PORT GPIOG
#define DISPLAY_RST_PIN GPIO_PIN_14

// Display data/command select (DISPL_DC) routed to FMC_A4
#define DISPLAY_DC_PORT GPIOF
#define DISPLAY_DC_PIN GPIO_PIN_4
#define DISPLAY_MEMORY_PIN 4

// Display power-supply enable (DISPL_PWR_EN, load switch)
#define DISPLAY_PWR_PORT GPIOF
#define DISPLAY_PWR_PIN GPIO_PIN_15

// Backlight: four LED strings driven as synchronized active-low PWM by
// TIM3 CH1-CH4 on PE3-PE6 (cathodes via 33R), with a common boost supply.
#define BACKLIGHT_PWM_TIM TIM3
#define BACKLIGHT_PWM_TIM_CLK_EN __HAL_RCC_TIM3_CLK_ENABLE
#define BACKLIGHT_PWM_TIM_CLK_DIS __HAL_RCC_TIM3_CLK_DISABLE
#define BACKLIGHT_PWM_TIM_FORCE_RESET __HAL_RCC_TIM3_FORCE_RESET
#define BACKLIGHT_PWM_TIM_RELEASE_RESET __HAL_RCC_TIM3_RELEASE_RESET
#define BACKLIGHT_PWM_TIM_AF GPIO_AF2_TIM3
#define BACKLIGHT_PWM_CHANNELS \
  {TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4}
#define BACKLIGHT_PWM_PORT GPIOE
#define BACKLIGHT_PWM_PORT_CLK_EN __HAL_RCC_GPIOE_CLK_ENABLE
#define BACKLIGHT_PWM_PINS (GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6)

#define I2C_COUNT 3
#define I2C_INSTANCE_0 I2C1
#define I2C_INSTANCE_0_CLK_EN __HAL_RCC_I2C1_CLK_ENABLE
#define I2C_INSTANCE_0_CLK_DIS __HAL_RCC_I2C1_CLK_DISABLE
#define I2C_INSTANCE_0_PIN_AF GPIO_AF4_I2C1
#define I2C_INSTANCE_0_SDA_PORT GPIOB
#define I2C_INSTANCE_0_SDA_PIN GPIO_PIN_9
#define I2C_INSTANCE_0_SDA_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
#define I2C_INSTANCE_0_SCL_PORT GPIOB
#define I2C_INSTANCE_0_SCL_PIN GPIO_PIN_8
#define I2C_INSTANCE_0_SCL_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
#define I2C_INSTANCE_0_RESET_REG &RCC->APB1RSTR1
#define I2C_INSTANCE_0_RESET_BIT RCC_APB1RSTR1_I2C1RST
#define I2C_INSTANCE_0_EV_IRQHandler I2C1_EV_IRQHandler
#define I2C_INSTANCE_0_ER_IRQHandler I2C1_ER_IRQHandler
#define I2C_INSTANCE_0_EV_IRQn I2C1_EV_IRQn
#define I2C_INSTANCE_0_ER_IRQn I2C1_ER_IRQn
#define I2C_INSTANCE_0_GUARD_TIME 0

#define I2C_INSTANCE_1 I2C2
#define I2C_INSTANCE_1_CLK_EN __HAL_RCC_I2C2_CLK_ENABLE
#define I2C_INSTANCE_1_CLK_DIS __HAL_RCC_I2C2_CLK_DISABLE
#define I2C_INSTANCE_1_PIN_AF GPIO_AF4_I2C2
#define I2C_INSTANCE_1_SDA_PORT GPIOB
#define I2C_INSTANCE_1_SDA_PIN GPIO_PIN_14
#define I2C_INSTANCE_1_SDA_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
#define I2C_INSTANCE_1_SCL_PORT GPIOB
#define I2C_INSTANCE_1_SCL_PIN GPIO_PIN_13
#define I2C_INSTANCE_1_SCL_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
#define I2C_INSTANCE_1_RESET_REG &RCC->APB1RSTR1
#define I2C_INSTANCE_1_RESET_BIT RCC_APB1RSTR1_I2C2RST
#define I2C_INSTANCE_1_EV_IRQHandler I2C2_EV_IRQHandler
#define I2C_INSTANCE_1_ER_IRQHandler I2C2_ER_IRQHandler
#define I2C_INSTANCE_1_EV_IRQn I2C2_EV_IRQn
#define I2C_INSTANCE_1_ER_IRQn I2C2_ER_IRQn
#define I2C_INSTANCE_1_GUARD_TIME 0

#define I2C_INSTANCE_2 I2C3
#define I2C_INSTANCE_2_CLK_EN __HAL_RCC_I2C3_CLK_ENABLE
#define I2C_INSTANCE_2_CLK_DIS __HAL_RCC_I2C3_CLK_DISABLE
#define I2C_INSTANCE_2_PIN_AF GPIO_AF4_I2C3
#define I2C_INSTANCE_2_SDA_PORT GPIOG
#define I2C_INSTANCE_2_SDA_PIN GPIO_PIN_8
#define I2C_INSTANCE_2_SDA_CLK_EN __HAL_RCC_GPIOG_CLK_ENABLE
#define I2C_INSTANCE_2_SCL_PORT GPIOG
#define I2C_INSTANCE_2_SCL_PIN GPIO_PIN_7
#define I2C_INSTANCE_2_SCL_CLK_EN __HAL_RCC_GPIOG_CLK_ENABLE
#define I2C_INSTANCE_2_RESET_REG &RCC->APB3RSTR
#define I2C_INSTANCE_2_RESET_BIT RCC_APB3RSTR_I2C3RST
#define I2C_INSTANCE_2_EV_IRQHandler I2C3_EV_IRQHandler
#define I2C_INSTANCE_2_ER_IRQHandler I2C3_ER_IRQHandler
#define I2C_INSTANCE_2_EV_IRQn I2C3_EV_IRQn
#define I2C_INSTANCE_2_ER_IRQn I2C3_ER_IRQn
#define I2C_INSTANCE_2_GUARD_TIME 50  // Optiga requires 50us guard time
#define I2C_INSTANCE_2_GTZC_PERIPH GTZC_PERIPH_I2C3

#define TOUCH_SENSITIVITY 0x40
#define TOUCH_I2C_INSTANCE 0
#define TOUCH_INT_PORT GPIOB
#define TOUCH_INT_PIN GPIO_PIN_11
#define TOUCH_ON_PORT GPIOG
#define TOUCH_ON_PIN GPIO_PIN_0

#define OPTIGA_I2C_INSTANCE 2
#define OPTIGA_RST_PORT GPIOF
#define OPTIGA_RST_PIN GPIO_PIN_13
#define OPTIGA_RST_CLK_EN __HAL_RCC_GPIOF_CLK_ENABLE
#define OPTIGA_PWR_PORT GPIOF
#define OPTIGA_PWR_PIN GPIO_PIN_12
#define OPTIGA_PWR_CLK_EN __HAL_RCC_GPIOF_CLK_ENABLE

// Nordic nRF54LS05A BLE radio.
// STM32 is the SPI slave (nRF is master) on SPI1; USART1 is the test/SMP link.
// NOTE: AF assignments (SPI1=AF5, USART1=AF7) should be verified against the
// STM32U585 datasheet alternate-function table for these specific pins.
#define NRF_SPI_INSTANCE SPI1
#define NRF_SPI_CLK_EN __HAL_RCC_SPI1_CLK_ENABLE
#define NRF_SPI_CLK_DIS __HAL_RCC_SPI1_CLK_DISABLE
#define NRF_SPI_FORCE_RESET __HAL_RCC_SPI1_FORCE_RESET
#define NRF_SPI_RELEASE_RESET __HAL_RCC_SPI1_RELEASE_RESET
#define NRF_SPI_PIN_AF GPIO_AF5_SPI1
#define NRF_SPI_DMA_RX_REQUEST GPDMA1_REQUEST_SPI1_RX
#define NRF_SPI_DMA_TX_REQUEST GPDMA1_REQUEST_SPI1_TX
#define NRF_SPI_INTERRUPT_HANDLER SPI1_IRQHandler
#define NRF_SPI_IRQN SPI1_IRQn
// BLE_SCK = PG2
#define NRF_SPI_SCK_PORT GPIOG
#define NRF_SPI_SCK_PIN GPIO_PIN_2
#define NRF_SPI_SCK_CLK_EN __HAL_RCC_GPIOG_CLK_ENABLE
// BLE_NSS = PE1
#define NRF_SPI_NSS_PORT GPIOE
#define NRF_SPI_NSS_PIN GPIO_PIN_1
#define NRF_SPI_NSS_CLK_EN __HAL_RCC_GPIOE_CLK_ENABLE
// BLE_MISO = PB4
#define NRF_SPI_MISO_PORT GPIOB
#define NRF_SPI_MISO_PIN GPIO_PIN_4
#define NRF_SPI_MISO_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
// BLE_MOSI = PB5
#define NRF_SPI_MOSI_PORT GPIOB
#define NRF_SPI_MOSI_PIN GPIO_PIN_5
#define NRF_SPI_MOSI_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE

// SPI_READY: STM32 -> nRF (BLE_GPIO1 = PC13)
#define NRF_OUT_SPI_READY_PIN GPIO_PIN_13
#define NRF_OUT_SPI_READY_PORT GPIOC
#define NRF_OUT_SPI_READY_CLK_ENA __HAL_RCC_GPIOC_CLK_ENABLE
// SPI_REQUEST: nRF -> STM32, EXTI (BLE_GPIO0 = PE0)
#define NRF_IN_SPI_REQUEST_PIN GPIO_PIN_0
#define NRF_IN_SPI_REQUEST_PORT GPIOE
#define NRF_IN_SPI_REQUEST_CLK_ENA __HAL_RCC_GPIOE_CLK_ENABLE
#define NRF_EXTI_INTERRUPT_GPIOSEL EXTI_GPIOE
#define NRF_EXTI_INTERRUPT_LINE EXTI_LINE_0
#define NRF_EXTI_INTERRUPT_PIN GPIO_PIN_0
#define NRF_EXTI_INTERRUPT_NUM EXTI0_IRQn
#define NRF_EXTI_INTERRUPT_HANDLER EXTI0_IRQHandler

// RESERVED: nRF -> STM32 (BLE_GPIO3 = PC7)
#define NRF_IN_RESERVED_PIN GPIO_PIN_7
#define NRF_IN_RESERVED_PORT GPIOC
#define NRF_IN_RESERVED_CLK_ENA __HAL_RCC_GPIOC_CLK_ENABLE
// RESET: STM32 -> nRF (BLE_RESET = PB7)
#define NRF_OUT_RESET_PIN GPIO_PIN_7
#define NRF_OUT_RESET_PORT GPIOB
#define NRF_OUT_RESET_CLK_ENA __HAL_RCC_GPIOB_CLK_ENABLE
// STAY_IN_BLD: STM32 -> nRF (BLE_GPIO2 = PE2)
#define NRF_OUT_STAY_IN_BLD_PIN GPIO_PIN_2
#define NRF_OUT_STAY_IN_BLD_PORT GPIOE
#define NRF_OUT_STAY_IN_BLD_CLK_ENA __HAL_RCC_GPIOE_CLK_ENABLE

#define NRF_UART_INSTANCE USART1
#define NRF_UART_CLK_EN __HAL_RCC_USART1_CLK_ENABLE
#define NRF_UART_CLK_DIS __HAL_RCC_USART1_CLK_DISABLE
#define NRF_UART_FORCE_RESET __HAL_RCC_USART1_FORCE_RESET
#define NRF_UART_RELEASE_RESET __HAL_RCC_USART1_RELEASE_RESET
#define NRF_UART_INTERRUPT_HANDLER USART1_IRQHandler
#define NRF_UART_IRQN USART1_IRQn
#define NRF_UART_PIN_AF GPIO_AF7_USART1
// BLE_TX = PB6
#define NRF_UART_TX_PORT GPIOB
#define NRF_UART_TX_PIN GPIO_PIN_6
#define NRF_UART_TX_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
// BLE_RX = PG10
#define NRF_UART_RX_PORT GPIOG
#define NRF_UART_RX_PIN GPIO_PIN_10
#define NRF_UART_RX_CLK_EN __HAL_RCC_GPIOG_CLK_ENABLE
// BLE_RTS = PG12
#define NRF_UART_RTS_PORT GPIOG
#define NRF_UART_RTS_PIN GPIO_PIN_12
#define NRF_UART_RTS_CLK_EN __HAL_RCC_GPIOG_CLK_ENABLE
// BLE_CTS = PG11
#define NRF_UART_CTS_PORT GPIOG
#define NRF_UART_CTS_PIN GPIO_PIN_11
#define NRF_UART_CTS_CLK_EN __HAL_RCC_GPIOG_CLK_ENABLE

// reserved, replace with real pins when available
#define HW_REVISION_PUPD GPIO_PULLUP
#define HW_REVISION_0_PIN GPIO_PIN_6
#define HW_REVISION_0_PORT GPIOF
#define HW_REVISION_0_CLOCK_ENABLE() __HAL_RCC_GPIOF_CLK_ENABLE()
#define HW_REVISION_1_PIN GPIO_PIN_7
#define HW_REVISION_1_PORT GPIOF
#define HW_REVISION_1_CLOCK_ENABLE() __HAL_RCC_GPIOF_CLK_ENABLE()
#define HW_REVISION_2_PIN GPIO_PIN_8
#define HW_REVISION_2_PORT GPIOF
#define HW_REVISION_2_CLOCK_ENABLE() __HAL_RCC_GPIOF_CLK_ENABLE()
#define HW_REVISION_3_PIN GPIO_PIN_9
#define HW_REVISION_3_PORT GPIOF
#define HW_REVISION_3_CLOCK_ENABLE() __HAL_RCC_GPIOF_CLK_ENABLE()
