header = "T3T2/boards/devkit.h"
emulator_header = "T3T2/boards/unix.h"

[display]
driver = "io/display_st7789"
panel = "io/display_panel_dem240320b1"

[backlight]
driver = "io/backlight_pwm"

[touch]
driver = "io/touch_ft6x36"
panel = "io/touch_panel_lx154a2422cpt23"

[optiga]

[tropic]

[ble]

[nrf]

[nrf_auth]
