# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class CardanoTxOutputType(p.MessageType):

    def __init__(
        self,
        address: str = None,
        address_n: List[int] = None,
        amount: int = None,
    ) -> None:
        self.address = address
        self.address_n = address_n if address_n is not None else []
        self.amount = amount

    @classmethod
    def get_fields(cls):
        return {
            1: ('address', p.UnicodeType, 0),
            2: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            3: ('amount', p.UVarintType, 0),
        }
