# Automatically generated by pb2py
# fmt: off
# isort:skip_file
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class EosActionSellRam(p.MessageType):

    def __init__(
        self,
        *,
        account: Optional[int] = None,
        bytes: Optional[int] = None,
    ) -> None:
        self.account = account
        self.bytes = bytes

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('account', p.UVarintType, None),
            2: ('bytes', p.UVarintType, None),
        }
