# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class EosPublicKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 601

    def __init__(
        self,
        *,
        wif_public_key: str,
        raw_public_key: bytes,
    ) -> None:
        self.wif_public_key = wif_public_key
        self.raw_public_key = raw_public_key

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('wif_public_key', p.UnicodeType, p.FLAG_REQUIRED),
            2: ('raw_public_key', p.BytesType, p.FLAG_REQUIRED),
        }
