# Automatically generated by pb2py
# fmt: off
import protobuf as p


class EosPermissionLevel(p.MessageType):

    def __init__(
        self,
        actor: int = None,
        permission: int = None,
    ) -> None:
        self.actor = actor
        self.permission = permission

    @classmethod
    def get_fields(cls):
        return {
            1: ('actor', p.UVarintType, 0),
            2: ('permission', p.UVarintType, 0),
        }
