# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .HederaId import HederaId

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class HederaTransactionID(p.MessageType):

    def __init__(
        self,
        *,
        accountID: HederaId = None,
    ) -> None:
        self.accountID = accountID

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            2: ('accountID', HederaId, None),
        }
