# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class LiskMultisignatureType(p.MessageType):

    def __init__(
        self,
        min: int = None,
        life_time: int = None,
        keys_group: List[str] = None,
    ) -> None:
        self.min = min
        self.life_time = life_time
        self.keys_group = keys_group if keys_group is not None else []

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('min', p.UVarintType, 0),
            2: ('life_time', p.UVarintType, 0),
            3: ('keys_group', p.UnicodeType, p.FLAG_REPEATED),
        }
