# Automatically generated by pb2py
# fmt: off
# isort:skip_file
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class MoneroAccountPublicAddress(p.MessageType):

    def __init__(
        self,
        *,
        spend_public_key: Optional[bytes] = None,
        view_public_key: Optional[bytes] = None,
    ) -> None:
        self.spend_public_key = spend_public_key
        self.view_public_key = view_public_key

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('spend_public_key', p.BytesType, None),
            2: ('view_public_key', p.BytesType, None),
        }
