# Automatically generated by pb2py
# fmt: off
# isort:skip_file
import protobuf as p

from .MoneroTransactionSourceEntry import MoneroTransactionSourceEntry

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class MoneroTransactionSignInputRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 515

    def __init__(
        self,
        *,
        src_entr: Optional[MoneroTransactionSourceEntry] = None,
        vini: Optional[bytes] = None,
        vini_hmac: Optional[bytes] = None,
        pseudo_out: Optional[bytes] = None,
        pseudo_out_hmac: Optional[bytes] = None,
        pseudo_out_alpha: Optional[bytes] = None,
        spend_key: Optional[bytes] = None,
        orig_idx: Optional[int] = None,
    ) -> None:
        self.src_entr = src_entr
        self.vini = vini
        self.vini_hmac = vini_hmac
        self.pseudo_out = pseudo_out
        self.pseudo_out_hmac = pseudo_out_hmac
        self.pseudo_out_alpha = pseudo_out_alpha
        self.spend_key = spend_key
        self.orig_idx = orig_idx

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('src_entr', MoneroTransactionSourceEntry, None),
            2: ('vini', p.BytesType, None),
            3: ('vini_hmac', p.BytesType, None),
            4: ('pseudo_out', p.BytesType, None),
            5: ('pseudo_out_hmac', p.BytesType, None),
            6: ('pseudo_out_alpha', p.BytesType, None),
            7: ('spend_key', p.BytesType, None),
            8: ('orig_idx', p.UVarintType, None),
        }
