# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NEM2CosignatureSignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 808

    def __init__(
        self,
        parent_hash: bytes = None,
        signature: bytes = None,
    ) -> None:
        self.parent_hash = parent_hash
        self.signature = signature

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('parent_hash', p.BytesType, 0),
            2: ('signature', p.BytesType, 0),
        }
