# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

ALLOW_INCOMING_ADDRESS = 1  # type: Literal[1]
ALLOW_MOSAIC = 2  # type: Literal[2]
ALLOW_INCOMING_TRANSACTION_TYPE = 4  # type: Literal[4]
ALLOW_OUTGOING_ADDRESS = 16385  # type: Literal[16385]
ALLOW_OUTGOING_TRANSACTION_TYPE = 16388  # type: Literal[16388]
BLOCK_INCOMING_ADDRESS = 32769  # type: Literal[32769]
BLOCK_MOSAIC = 32770  # type: Literal[32770]
BLOCK_INCOMING_TRANSACTION_TYPE = 32772  # type: Literal[32772]
BLOCK_OUTGOING_ADDRESS = 49153  # type: Literal[49153]
BLOCK_OUTGOING_TRANSACTION_TYPE = 49156  # type: Literal[49156]
