# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NEMMosaic(p.MessageType):

    def __init__(
        self,
        mosaic_id: int = None,
        amount: int = None,
    ) -> None:
        self.mosaic_id = mosaic_id
        self.amount = amount

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('mosaic_id', p.UVarintType, 0),
            2: ('amount', p.UVarintType, 0),
        }
