# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .RipplePath import RipplePath

if __debug__:
    try:
        from typing import Dict, List, Optional
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class RipplePathArray(p.MessageType):

    def __init__(
        self,
        path: List[RipplePath] = None,
    ) -> None:
        self.path = path if path is not None else []

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('path', RipplePath, p.FLAG_REPEATED),
        }
