# Automatically generated by pb2py
# fmt: off
import protobuf as p
from apps.vsys.constants import PROTOCOL, OPC_ACCOUNT

if __debug__:
    try:
        from typing import Dict, List, Optional
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class VsysAddress(p.MessageType):
    MESSAGE_WIRE_TYPE = 1001

    def __init__(
        self,
        api: int = None,
        address: str = None
    ) -> None:
        self.protocol = PROTOCOL
        self.api = api
        self.opc = OPC_ACCOUNT
        self.address = address

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('protocol', p.UnicodeType, 0),
            2: ('api', p.UVarintType, 0),
            3: ('opc', p.UnicodeType, 0),
            4: ('address', p.UnicodeType, 0),
        }
