# Automatically generated by pb2py
# fmt: off
import protobuf as p


class WordAck(p.MessageType):
    MESSAGE_WIRE_TYPE = 47

    def __init__(
        self,
        word: str = None,
    ) -> None:
        self.word = word

    @classmethod
    def get_fields(cls):
        return {
            1: ('word', p.UnicodeType, 0),  # required
        }
