# Automatically generated by pb2py
from __future__ import absolute_import
from .. import protobuf as p


class ChangePin(p.MessageType):
    FIELDS = {
        1: ('remove', p.BoolType, 0),
    }
    MESSAGE_WIRE_TYPE = 4
