# Automatically generated by pb2py
from __future__ import absolute_import
from .. import protobuf as p


class DebugLinkMemory(p.MessageType):
    FIELDS = {
        1: ('memory', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 111
