# Automatically generated by pb2py
from __future__ import absolute_import
from .. import protobuf as p


class Failure(p.MessageType):
    FIELDS = {
        1: ('code', p.UVarintType, 0),
        2: ('message', p.UnicodeType, 0),
    }
    MESSAGE_WIRE_TYPE = 3
