# Automatically generated by pb2py
from .. import protobuf as p


class StellarSignTx(p.MessageType):
    FIELDS = {
        1: ('protocol_version', p.UVarintType, 0),
        2: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        3: ('network_passphrase', p.UnicodeType, 0),
        4: ('source_account', p.BytesType, 0),
        5: ('fee', p.UVarintType, 0),
        6: ('sequence_number', p.UVarintType, 0),
        8: ('timebounds_start', p.UVarintType, 0),
        9: ('timebounds_end', p.UVarintType, 0),
        10: ('memo_type', p.UVarintType, 0),
        11: ('memo_text', p.UnicodeType, 0),
        12: ('memo_id', p.UVarintType, 0),
        13: ('memo_hash', p.BytesType, 0),
        14: ('num_operations', p.UVarintType, 0),
    }
    MESSAGE_WIRE_TYPE = 202
