# Automatically generated by pb2py
from .. import protobuf as p


class StellarBumpSequenceOp(p.MessageType):
    FIELDS = {
        1: ('source_account', p.BytesType, 0),
        2: ('bump_to', p.UVarintType, 0),
    }
    MESSAGE_WIRE_TYPE = 221
