# Automatically generated by pb2py
from .. import protobuf as p


class StellarSignMessage(p.MessageType):
    FIELDS = {
        1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        2: ('message', p.UnicodeType, 0),
    }
    MESSAGE_WIRE_TYPE = 204
