# Automatically generated by pb2py
from .. import protobuf as p


class StellarManageDataOp(p.MessageType):
    FIELDS = {
        1: ('source_account', p.BytesType, 0),
        2: ('key', p.UnicodeType, 0),
        3: ('value', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 220
