NAME = speed

OBJS += rand.o
OBJS += speed.o

OBJS += ../bignum.o
OBJS += ../bip32.o
OBJS += ../ecdsa.o
OBJS += ../hmac.o
OBJS += ../ripemd160.o
OBJS += ../secp256k1.o
OBJS += ../sha2.o

include Makefile.include

CFLAGS += -I..
