import pytest
from apdu import (
    ApduRequest,
    ApduResponse,
    DataTooShort,
    InvalidCla,
    InvalidIns,
    InvalidLe,
    InvalidP1,
    InvalidP2,
    TrailingBytes,
)

H = bytes.fromhex

# TODO: These test vectors were generated by AI


ENCODE_REQUEST_VECTORS = [
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, b"", None),
        H("00A40400"),
        id="case1-header-only",
    ),
    pytest.param(
        ApduRequest(0x80, 0xCA, 0x00, 0x00, b"", 1),
        H("80CA0000 01"),
        id="case2s-le-1-min",
    ),
    pytest.param(
        ApduRequest(0x80, 0xCA, 0x00, 0x00, b"", 10),
        H("80CA0000 0A"),
        id="case2s-le-10",
    ),
    pytest.param(
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 255),
        H("00B00000 FF"),
        id="case2s-le-255",
    ),
    pytest.param(
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 256),
        H("00B00000 00"),
        id="case2s-le-256-encoded-as-0x00",
    ),
    pytest.param(
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 257),
        H("00B00000 00 0101"),
        id="case2e-le-257-min-extended",
    ),
    pytest.param(
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 1000),
        H("00B00000 00 03E8"),
        id="case2e-le-1000",
    ),
    pytest.param(
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 65535),
        H("00B00000 00 FFFF"),
        id="case2e-le-65535",
    ),
    pytest.param(
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 65536),
        H("00B00000 00 0000"),
        id="case2e-le-65536-encoded-as-0x0000",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, b"\xaa", None),
        H("00D60000 01 AA"),
        id="case3s-data-1-byte-min",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, H("010203"), None),
        H("00D60000 03 010203"),
        id="case3s-data-3-bytes",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(range(255)), None),
        H("00D60000 FF") + bytes(range(255)),
        id="case3s-data-255-bytes-max-short",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(256), None),
        H("00D60000 00 0100") + bytes(256),
        id="case3e-data-256-bytes-min-extended",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(300), None),
        H("00D60000 00 012C") + bytes(300),
        id="case3e-data-300-bytes",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, H("AABB"), 16),
        H("00A40400 02 AABB 10"),
        id="case4s-data-2-le-16",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, b"\x01", 1),
        H("00A40400 01 01 01"),
        id="case4s-data-1-le-1-min-both",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, bytes(range(255)), 256),
        H("00A40400 FF") + bytes(range(255)) + H("00"),
        id="case4s-data-255-le-256-max-short",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(300), 100),
        H("00D60000 00 012C") + bytes(300) + H("0064"),
        id="case4e-data-300-le-100-extended-by-data",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(256), 65536),
        H("00D60000 00 0100") + bytes(256) + H("0000"),
        id="case4e-data-256-le-65536",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, H("AABB"), 257),
        H("00A40400 00 0002 AABB 0101"),
        id="case4e-data-2-le-257-extended-by-le",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, b"\x01", 1000),
        H("00A40400 00 0001 01 03E8"),
        id="case4e-data-1-le-1000",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, H("A00000095901"), None),
        H("00A40400 06 A00000095901"),
        id="select-aid-a00000095901",
    ),
    pytest.param(
        ApduRequest(0xFF, 0xFF, 0xFF, 0xFF, b"", None),
        H("FFFFFFFF"),
        id="case1-all-header-bytes-0xff",
    ),
    pytest.param(
        ApduRequest(0x00, 0x00, 0x00, 0x00, b"", None),
        H("00000000"),
        id="case1-all-header-bytes-0x00",
    ),
]


@pytest.mark.parametrize("apdu, expected_raw_apdu", ENCODE_REQUEST_VECTORS)
def test_encode_request(apdu: ApduRequest, expected_raw_apdu: bytes):
    assert apdu.to_bytes() == expected_raw_apdu


ENCODE_REQUEST_ERROR_VECTORS = [
    pytest.param(
        ApduRequest(0x100, 0xA4, 0x04, 0x00, b"", None), InvalidCla, id="cla-256"
    ),
    pytest.param(
        ApduRequest(-1, 0xA4, 0x04, 0x00, b"", None), InvalidCla, id="cla-negative"
    ),
    pytest.param(
        ApduRequest(0x00, 256, 0x04, 0x00, b"", None), InvalidIns, id="ins-256"
    ),
    pytest.param(
        ApduRequest(0x00, -1, 0x04, 0x00, b"", None), InvalidIns, id="ins-negative"
    ),
    pytest.param(ApduRequest(0x00, 0xA4, 256, 0x00, b"", None), InvalidP1, id="p1-256"),
    pytest.param(
        ApduRequest(0x00, 0xA4, -1, 0x00, b"", None), InvalidP1, id="p1-negative"
    ),
    pytest.param(ApduRequest(0x00, 0xA4, 0x04, 256, b"", None), InvalidP2, id="p2-256"),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, -1, b"", None), InvalidP2, id="p2-negative"
    ),
    pytest.param(ApduRequest(0x00, 0xA4, 0x04, 0x00, b"", 0), InvalidLe, id="le-0"),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, b"", -1), InvalidLe, id="le-negative"
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, b"", 65537), InvalidLe, id="le-65537"
    ),
]


@pytest.mark.parametrize("apdu, expected_exception", ENCODE_REQUEST_ERROR_VECTORS)
def test_encode_request_rejects_invalid_fields(apdu: ApduRequest, expected_exception):
    with pytest.raises(expected_exception):
        apdu.to_bytes()


DECODE_REQUEST_VECTORS = [
    pytest.param(
        H("00A40400"),
        ApduRequest(0x00, 0xA4, 0x04, 0x00, b"", None),
        id="case1-header-only",
    ),
    pytest.param(
        H("FFFFFFFF"),
        ApduRequest(0xFF, 0xFF, 0xFF, 0xFF, b"", None),
        id="case1-all-0xff",
    ),
    pytest.param(
        H("80CA0000 01"),
        ApduRequest(0x80, 0xCA, 0x00, 0x00, b"", 1),
        id="case2s-le-1",
    ),
    pytest.param(
        H("80CA0000 0A"),
        ApduRequest(0x80, 0xCA, 0x00, 0x00, b"", 10),
        id="case2s-le-10",
    ),
    pytest.param(
        H("00B00000 FF"),
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 255),
        id="case2s-le-255",
    ),
    pytest.param(
        H("00B00000 00"),
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 256),
        id="case2s-le-0x00-means-256",
    ),
    pytest.param(
        H("00B00000 00 0001"),
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 1),
        id="case2e-le-1",
    ),
    pytest.param(
        H("00B00000 00 0101"),
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 257),
        id="case2e-le-257",
    ),
    pytest.param(
        H("00B00000 00 03E8"),
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 1000),
        id="case2e-le-1000",
    ),
    pytest.param(
        H("00B00000 00 FFFF"),
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 65535),
        id="case2e-le-65535",
    ),
    pytest.param(
        H("00B00000 00 0000"),
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 65536),
        id="case2e-le-0x0000-means-65536",
    ),
    pytest.param(
        H("00D60000 01 FF"),
        ApduRequest(0x00, 0xD6, 0x00, 0x00, b"\xff", None),
        id="case3s-data-1-byte",
    ),
    pytest.param(
        H("00D60000 03 010203"),
        ApduRequest(0x00, 0xD6, 0x00, 0x00, H("010203"), None),
        id="case3s-data-3-bytes",
    ),
    pytest.param(
        H("00D60000 FF") + bytes(range(255)),
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(range(255)), None),
        id="case3s-data-255-bytes-max",
    ),
    pytest.param(
        H("00D60000 00 0100") + bytes(256),
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(256), None),
        id="case3e-data-256-bytes",
    ),
    pytest.param(
        H("00D60000 00 012C") + bytes(300),
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(300), None),
        id="case3e-data-300-bytes",
    ),
    pytest.param(
        H("00D60000 00 0001 FF"),
        ApduRequest(0x00, 0xD6, 0x00, 0x00, b"\xff", None),
        id="case3e-data-1-byte-in-extended-encoding",
    ),
    pytest.param(
        H("00A40400 02 AABB 10"),
        ApduRequest(0x00, 0xA4, 0x04, 0x00, H("AABB"), 16),
        id="case4s-data-2-le-16",
    ),
    pytest.param(
        H("00A40400 01 01 01"),
        ApduRequest(0x00, 0xA4, 0x04, 0x00, b"\x01", 1),
        id="case4s-data-1-le-1-min-both",
    ),
    pytest.param(
        H("00A40400 01 FF 00"),
        ApduRequest(0x00, 0xA4, 0x04, 0x00, b"\xff", 256),
        id="case4s-data-1-le-256",
    ),
    pytest.param(
        H("00A40400 FF") + bytes(range(255)) + H("00"),
        ApduRequest(0x00, 0xA4, 0x04, 0x00, bytes(range(255)), 256),
        id="case4s-data-255-le-256-max-short",
    ),
    pytest.param(
        H("00D60000 00 012C") + bytes(300) + H("0064"),
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(300), 100),
        id="case4e-data-300-le-100",
    ),
    pytest.param(
        H("00D60000 00 0100") + bytes(256) + H("0000"),
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(256), 65536),
        id="case4e-data-256-le-65536",
    ),
    pytest.param(
        H("00A40400 00 0002 AABB 0101"),
        ApduRequest(0x00, 0xA4, 0x04, 0x00, H("AABB"), 257),
        id="case4e-data-2-le-257-in-extended",
    ),
    pytest.param(
        H("00D60000 00 0001 FF FFFF"),
        ApduRequest(0x00, 0xD6, 0x00, 0x00, b"\xff", 65535),
        id="case4e-data-1-le-65535-in-extended",
    ),
    pytest.param(
        H("00D60000 00 0001 FF 0000"),
        ApduRequest(0x00, 0xD6, 0x00, 0x00, b"\xff", 65536),
        id="case4e-data-1-le-65536-in-extended",
    ),
]


@pytest.mark.parametrize("raw_apdu, expected_apdu", DECODE_REQUEST_VECTORS)
def test_decode_request(raw_apdu: bytes, expected_apdu: ApduRequest):
    decoded = ApduRequest.from_bytes(raw_apdu)
    assert decoded.cla == expected_apdu.cla
    assert decoded.ins == expected_apdu.ins
    assert decoded.p1 == expected_apdu.p1
    assert decoded.p2 == expected_apdu.p2
    assert decoded.data == expected_apdu.data
    assert decoded.le == expected_apdu.le


DECODE_REQUEST_ERROR_VECTORS = [
    pytest.param(b"", DataTooShort, id="empty"),
    pytest.param(H("00"), DataTooShort, id="1-byte"),
    pytest.param(H("00A4"), DataTooShort, id="2-bytes"),
    pytest.param(H("00A404"), DataTooShort, id="3-bytes"),
    pytest.param(
        H("00D60000 05 0102"), DataTooShort, id="short-lc-5-only-2-data-bytes"
    ),
    pytest.param(
        H("00D60000 03 0102"), DataTooShort, id="short-lc-3-only-2-data-bytes"
    ),
    pytest.param(
        H("00D60000 01 FF AABB"),
        TrailingBytes,
        id="short-trailing-2-bytes-after-data",
    ),
    pytest.param(
        H("00D60000 02 AABB CCDDEE"),
        TrailingBytes,
        id="short-trailing-3-bytes-after-data",
    ),
    pytest.param(
        H("00B00000 00 01"),
        DataTooShort,
        id="extended-body-too-short-2-bytes",
    ),
    pytest.param(
        H("00D60000 00 0100") + bytes(100),
        DataTooShort,
        id="extended-lc-256-only-100-data-bytes",
    ),
    pytest.param(
        H("00D60000 00 0100") + bytes(256) + H("01"),
        TrailingBytes,
        id="extended-trailing-1-byte-after-data",
    ),
    pytest.param(
        H("00D60000 00 0100") + bytes(256) + H("010203"),
        TrailingBytes,
        id="extended-trailing-3-bytes-after-data",
    ),
]


@pytest.mark.parametrize("raw_apdu, expected_exception", DECODE_REQUEST_ERROR_VECTORS)
def test_decode_request_rejects_malformed_input(raw_apdu: bytes, expected_exception):
    with pytest.raises(expected_exception):
        ApduRequest.from_bytes(raw_apdu)


ENCODE_RESPONSE_VECTORS = [
    pytest.param(
        ApduResponse(0x90, 0x00, b""),
        H("9000"),
        id="status-only-success",
    ),
    pytest.param(
        ApduResponse(0x6A, 0x82, b""),
        H("6A82"),
        id="status-only-file-not-found",
    ),
    pytest.param(
        ApduResponse(0x69, 0x82, b""),
        H("6982"),
        id="status-only-security-not-satisfied",
    ),
    pytest.param(
        ApduResponse(0x6A, 0x86, b""),
        H("6A86"),
        id="status-only-incorrect-p1p2",
    ),
    pytest.param(
        ApduResponse(0x61, 0x10, b""),
        H("6110"),
        id="status-only-sw2-bytes-remaining",
    ),
    pytest.param(
        ApduResponse(0x90, 0x00, H("010203")),
        H("010203 9000"),
        id="3-bytes-data-success",
    ),
    pytest.param(
        ApduResponse(0x90, 0x00, b"\xff"),
        H("FF 9000"),
        id="1-byte-data",
    ),
    pytest.param(
        ApduResponse(0x90, 0x00, bytes(range(256)) * 4),
        bytes(range(256)) * 4 + H("9000"),
        id="large-1024-byte-response",
    ),
    pytest.param(
        ApduResponse(0x6C, 0x20, H("DEADBEEF")),
        H("DEADBEEF 6C20"),
        id="data-with-error-status",
    ),
]


@pytest.mark.parametrize("apdu, expected_raw_apdu", ENCODE_RESPONSE_VECTORS)
def test_encode_response(apdu: ApduResponse, expected_raw_apdu: bytes):
    assert apdu.to_bytes() == expected_raw_apdu


DECODE_RESPONSE_VECTORS = [
    pytest.param(
        H("9000"),
        ApduResponse(0x90, 0x00, b""),
        id="status-only-success",
    ),
    pytest.param(
        H("6A82"),
        ApduResponse(0x6A, 0x82, b""),
        id="status-only-file-not-found",
    ),
    pytest.param(
        H("010203 9000"),
        ApduResponse(0x90, 0x00, H("010203")),
        id="3-bytes-data-success",
    ),
    pytest.param(
        H("FF 9000"),
        ApduResponse(0x90, 0x00, b"\xff"),
        id="1-byte-data",
    ),
    pytest.param(
        bytes(range(256)) * 4 + H("9000"),
        ApduResponse(0x90, 0x00, bytes(range(256)) * 4),
        id="large-1024-byte-response",
    ),
    pytest.param(
        H("DEADBEEF 6C20"),
        ApduResponse(0x6C, 0x20, H("DEADBEEF")),
        id="data-with-error-status",
    ),
    pytest.param(
        H("0000"),
        ApduResponse(0x00, 0x00, b""),
        id="sw1-sw2-both-zero",
    ),
    pytest.param(
        H("FFFF"),
        ApduResponse(0xFF, 0xFF, b""),
        id="sw1-sw2-both-0xff",
    ),
]


@pytest.mark.parametrize("raw_apdu, expected_apdu", DECODE_RESPONSE_VECTORS)
def test_decode_response(raw_apdu: bytes, expected_apdu: ApduResponse):
    decoded = ApduResponse.from_bytes(raw_apdu)
    assert decoded.sw1 == expected_apdu.sw1
    assert decoded.sw2 == expected_apdu.sw2
    assert decoded.response == expected_apdu.response


DECODE_RESPONSE_ERROR_VECTORS = [
    pytest.param(b"", DataTooShort, id="empty"),
    pytest.param(H("90"), DataTooShort, id="1-byte"),
]


@pytest.mark.parametrize("raw_apdu, expected_exception", DECODE_RESPONSE_ERROR_VECTORS)
def test_decode_response_rejects_too_short_input(raw_apdu: bytes, expected_exception):
    with pytest.raises(expected_exception):
        ApduResponse.from_bytes(raw_apdu)


ROUNDTRIP_REQUEST_VECTORS = [
    pytest.param(ApduRequest(0x00, 0xA4, 0x04, 0x00, b"", None), id="case1"),
    pytest.param(ApduRequest(0x80, 0xCA, 0x00, 0x00, b"", 1), id="case2s-le-1"),
    pytest.param(ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 42), id="case2s-le-42"),
    pytest.param(ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 255), id="case2s-le-255"),
    pytest.param(ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 256), id="case2s-le-256"),
    pytest.param(ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 257), id="case2e-le-257"),
    pytest.param(ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 1000), id="case2e-le-1000"),
    pytest.param(ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 65535), id="case2e-le-65535"),
    pytest.param(ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 65536), id="case2e-le-65536"),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, b"\x42", None), id="case3s-1-byte"
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, H("DEADBEEF"), None),
        id="case3s-4-bytes",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(range(255)), None),
        id="case3s-255-bytes",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(256), None),
        id="case3e-256-bytes",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(range(256)) * 2, None),
        id="case3e-512-bytes",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, H("010203"), 128),
        id="case4s-data-3-le-128",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, b"\x01", 256),
        id="case4s-data-1-le-256",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, bytes(range(255)), 256),
        id="case4s-data-255-le-256-max-short",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(range(256)) * 2, 512),
        id="case4e-data-512-le-512",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(300), 65536),
        id="case4e-data-300-le-65536",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, H("FF"), 1000),
        id="case4e-data-1-le-1000-extended-by-le",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, H("A00000095901"), None),
        id="select-aid",
    ),
    pytest.param(
        ApduRequest(0xFF, 0xFF, 0xFF, 0xFF, b"", None),
        id="all-header-0xff",
    ),
    pytest.param(
        ApduRequest(0x00, 0x00, 0x00, 0x00, b"", None),
        id="all-header-0x00",
    ),
]


@pytest.mark.parametrize("original_apdu", ROUNDTRIP_REQUEST_VECTORS)
def test_request_survives_encode_decode_roundtrip(original_apdu: ApduRequest):
    encoded = original_apdu.to_bytes()
    decoded = ApduRequest.from_bytes(encoded)
    assert decoded == original_apdu


ROUNDTRIP_RESPONSE_VECTORS = [
    pytest.param(ApduResponse(0x90, 0x00, b""), id="success-no-data"),
    pytest.param(ApduResponse(0x6A, 0x82, b""), id="error-no-data"),
    pytest.param(ApduResponse(0x69, 0x82, b""), id="security-error"),
    pytest.param(ApduResponse(0x90, 0x00, bytes(range(64))), id="success-64-bytes"),
    pytest.param(ApduResponse(0x90, 0x00, b"\xff"), id="success-1-byte"),
    pytest.param(
        ApduResponse(0x90, 0x00, bytes(range(256)) * 4),
        id="success-1024-bytes",
    ),
    pytest.param(ApduResponse(0x00, 0x00, b""), id="sw-0x0000"),
    pytest.param(ApduResponse(0xFF, 0xFF, b""), id="sw-0xffff"),
    pytest.param(ApduResponse(0x61, 0x00, H("CAFE")), id="sw-6100-with-data"),
]


@pytest.mark.parametrize("original_apdu", ROUNDTRIP_RESPONSE_VECTORS)
def test_response_survives_encode_decode_roundtrip(original_apdu: ApduResponse):
    encoded = original_apdu.to_bytes()
    decoded = ApduResponse.from_bytes(encoded)
    assert decoded == original_apdu


ENCODE_REQUEST_LENGTH_VECTORS = [
    pytest.param(ApduRequest(0x00, 0xA4, 0x04, 0x00, b"", None), 4, id="case1-len-4"),
    pytest.param(ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 10), 5, id="case2s-len-5"),
    pytest.param(
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 256), 5, id="case2s-le256-len-5"
    ),
    pytest.param(ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 1000), 7, id="case2e-len-7"),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, H("AABB"), None),
        4 + 1 + 2,
        id="case3s-len-header+lc+data",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(256), None),
        4 + 1 + 2 + 256,
        id="case3e-len-header+marker+lc2+data",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, H("AABB"), 16),
        4 + 1 + 2 + 1,
        id="case4s-len-header+lc+data+le",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(300), 100),
        4 + 1 + 2 + 300 + 2,
        id="case4e-len-header+marker+lc2+data+le2",
    ),
]


@pytest.mark.parametrize("apdu, expected_length", ENCODE_REQUEST_LENGTH_VECTORS)
def test_encode_request_produces_correct_length(
    apdu: ApduRequest, expected_length: int
):
    assert len(apdu.to_bytes()) == expected_length


ENCODE_RESPONSE_LENGTH_VECTORS = [
    pytest.param(ApduResponse(0x90, 0x00, b""), 2, id="status-only-len-2"),
    pytest.param(ApduResponse(0x90, 0x00, H("010203")), 5, id="3-bytes-data-len-5"),
    pytest.param(
        ApduResponse(0x90, 0x00, bytes(1000)),
        1002,
        id="1000-bytes-data-len-1002",
    ),
]


@pytest.mark.parametrize("apdu, expected_length", ENCODE_RESPONSE_LENGTH_VECTORS)
def test_encode_response_produces_correct_length(
    apdu: ApduResponse, expected_length: int
):
    assert len(apdu.to_bytes()) == expected_length


HEADER_PREFIX_VECTORS = [
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, b"", None), H("00A40400"), id="case1"
    ),
    pytest.param(
        ApduRequest(0x80, 0xCA, 0x01, 0x02, b"", 10), H("80CA0102"), id="case2s"
    ),
    pytest.param(
        ApduRequest(0x00, 0xB0, 0x00, 0x00, b"", 1000), H("00B00000"), id="case2e"
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, H("FF"), None),
        H("00D60000"),
        id="case3s",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(300), None),
        H("00D60000"),
        id="case3e",
    ),
    pytest.param(
        ApduRequest(0x00, 0xA4, 0x04, 0x00, H("FF"), 10),
        H("00A40400"),
        id="case4s",
    ),
    pytest.param(
        ApduRequest(0x00, 0xD6, 0x00, 0x00, bytes(300), 100),
        H("00D60000"),
        id="case4e",
    ),
]


@pytest.mark.parametrize("apdu, expected_header_prefix", HEADER_PREFIX_VECTORS)
def test_encoded_request_starts_with_header_bytes(
    apdu: ApduRequest, expected_header_prefix: bytes
):
    assert apdu.to_bytes()[:4] == expected_header_prefix


RESPONSE_STATUS_SUFFIX_VECTORS = [
    pytest.param(ApduResponse(0x90, 0x00, b""), H("9000"), id="success"),
    pytest.param(ApduResponse(0x6A, 0x82, b""), H("6A82"), id="error"),
    pytest.param(ApduResponse(0x90, 0x00, bytes(500)), H("9000"), id="large-data"),
]


@pytest.mark.parametrize("apdu, expected_status_suffix", RESPONSE_STATUS_SUFFIX_VECTORS)
def test_encoded_response_ends_with_status_bytes(
    apdu: ApduResponse, expected_status_suffix: bytes
):
    assert apdu.to_bytes()[-2:] == expected_status_suffix
