uses = [
    "backlight",
    "backup_ram",
    "ble",
    "boot_ucb",
    "button",
    "consumption_mask",
    "display",
    "dma2d",
    "framebuffer",
    "haptic",
    "hash_processor",
    "hw_jpeg_decoder",
    "lockable_bootloader",
    "mcu_attestation",
    "nrf",
    "nrf_auth",
    "optiga",
    "power_manager",
    "pvd",
    "rgb_led",
    "rtc",
    "sd_card",
    "sdram",
    "secmon_layout",
    "secure_mode",
    "secret",
    "secure_aes",
    "smp",
    "suspend",
    "tamper",
    "telemetry",
    "touch",
    "touch_wakeup",
    "tropic",
    "usb",
]

elf_sections = [".flash", ".data"]
