name: 'UI report'
description: 'Prepare and upload HTML report of UI test results'
inputs:
  model:
    description: 'Internal model name'
    required: true
runs:
  using: composite
  steps:
    - run: |
        MODELJOB=${{ inputs.model }}-${{ github.job }}
        OUTDIR=${{ github.run_id }}/$MODELJOB
        mkdir -p $OUTDIR
        nix-shell --run "poetry run python ci/prepare_ui_artifacts.py || true"
        mv tests/ui_tests/reports/test/* $OUTDIR || true
        mv tests/ui_tests/fixtures.*.json $OUTDIR || true
        mv tests/trezor.log $OUTDIR || true
        diff -u tests/ui_tests/fixtures.json tests/ui_tests/fixtures.suggestion.json || true
        tar -cf screens_$MODELJOB.tar tests/ui_tests/screens || true
        tar -cf ui_test_records_$MODELJOB.tar ci/ui_test_records || true
      shell: sh
    - run: |
        chmod 600 ./ssh-id
        nix-shell -p rsync -p openssh --run "rsync -av -e 'ssh -i ./ssh-id -o StrictHostKeyChecking=off' ${{ github.run_id }} ui@trezorui.martinmilata.cz:ci-storage"
      shell: sh
    - uses: actions/upload-artifact@v3
      with:
        name: ui-records
        path: |
          # used by core_ui_deploy
          ui_test_records_${{ inputs.model }}-${{ github.job }}.tar
          # used by core_ui_master
          screens_${{ inputs.model }}-${{ github.job }}.tar
        retention-days: 1  # not useful after workflow finishes
