# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: ba167d9f3db4abbdc9b67887ca3ea66c64f2d956 #v3.3.0
      import: true
    - name: mcuboot
      url: https://github.com/trezor/mcuboot
      revision: de2be1c9718ccf531ad1d85ce35e4926faabe92e #trezor-ncs3.3.0
      path: bootloader/mcuboot

