# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v2.9.0
      import: true

# Temporarily disable mcuboot fork until it's ready
#    - name: mcuboot
#      url: https://github.com/trezor/mcuboot
#      revision: v2.1.0-ncs3
#      path: bootloader/mcuboot

