# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: b5f643e153d95c909d2f54c98a39f5697101c5e8 #v3.3.0 preview 3
      import: true
    - name: mcuboot
      url: https://github.com/trezor/mcuboot
      revision: 2daf62da207fd93fd54b15d1ac6b163540c1ebef # 330 test
      path: bootloader/mcuboot

