# Automatically generated by pb2py
# fmt: off
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

BITCOIN: Literal[0] = 0
MILLIBITCOIN: Literal[1] = 1
MICROBITCOIN: Literal[2] = 2
SATOSHI: Literal[3] = 3
