# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .NEM2Address import NEM2Address
from .NEM2Mosaic import NEM2Mosaic
from .NEM2TransferMessage import NEM2TransferMessage

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NEM2TransferTransaction(p.MessageType):

    def __init__(
        self,
        recipient_address: NEM2Address = None,
        message: NEM2TransferMessage = None,
        mosaics: List[NEM2Mosaic] = None,
    ) -> None:
        self.recipient_address = recipient_address
        self.message = message
        self.mosaics = mosaics if mosaics is not None else []

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('recipient_address', NEM2Address, 0),
            2: ('message', NEM2TransferMessage, 0),
            3: ('mosaics', NEM2Mosaic, p.FLAG_REPEATED),
        }
