# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

RESERVED = 0  # type: Literal[0]
TRANSFER = 16724  # type: Literal[16724]
MOSAIC_DEFINITION = 16717  # type: Literal[16717]
MOSAIC_SUPPLY_CHANGE = 16973  # type: Literal[16973]
NAMESPACE_REGISTRATION = 16718  # type: Literal[16718]
ADDRESS_ALIAS = 16974  # type: Literal[16974]
AGGREGATE_BONDED = 16961  # type: Literal[16961]
AGGREGATE_COMPLETE = 16705  # type: Literal[16705]
NAMESPACE_METADATA = 17220  # type: Literal[17220]
MOSAIC_METADATA = 16964  # type: Literal[16964]
ACCOUNT_METADATA = 16708  # type: Literal[16708]
MOSAIC_ALIAS = 17230  # type: Literal[17230]
HASH_LOCK = 16712  # type: Literal[16712]
SECRET_LOCK = 16722  # type: Literal[16722]
SECRET_PROOF = 16978  # type: Literal[16978]
MULTISIG_MODIFICATION = 16725  # type: Literal[16725]
ACCOUNT_ADDRESS_RESTRICTION = 16720  # type: Literal[16720]
ACCOUNT_MOSAIC_RESTRICTION = 16976  # type: Literal[16976]
ACCOUNT_OPERATION_RESTRICTION = 17232  # type: Literal[17232]
