# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

MAIN_NET = 104  # type: Literal[104]
TEST_NET = 152  # type: Literal[152]
MIJIN = 96  # type: Literal[96]
MIJIN_TEST = 144  # type: Literal[144]
