# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class TezosRevealOp(p.MessageType):

    def __init__(
        self,
        *,
        source: bytes = None,
        fee: int = None,
        counter: int = None,
        gas_limit: int = None,
        storage_limit: int = None,
        public_key: bytes = None,
    ) -> None:
        self.source = source
        self.fee = fee
        self.counter = counter
        self.gas_limit = gas_limit
        self.storage_limit = storage_limit
        self.public_key = public_key

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            7: ('source', p.BytesType, None),
            2: ('fee', p.UVarintType, None),
            3: ('counter', p.UVarintType, None),
            4: ('gas_limit', p.UVarintType, None),
            5: ('storage_limit', p.UVarintType, None),
            6: ('public_key', p.BytesType, None),
        }
