# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .TronVote import TronVote

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class TronVoteWitnessContract(p.MessageType):

    def __init__(
        self,
        votes: List[TronVote] = None,
    ) -> None:
        self.votes = votes if votes is not None else []

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('votes', TronVote, p.FLAG_REPEATED),
        }
