#!/usr/bin/env bash
RETURN=0

EXCEPTIONS=()
EXCEPTIONS+=( "decred" )  # "decred" figures in field names used by the bitcoin app
EXCEPTIONS+=( "omni" )  # OMNI is part of the bitcoin app
    # BIP39 or SLIP39 words that have "dash" in them
EXCEPTIONS+=( "dash" )
EXCEPTIONS+=( "confirm_ethereum_tx" )  # is model-specific, so is in layout/__init__.py instead of ethereum/layout.py

GREP_ARGS=()
for exception in "${EXCEPTIONS[@]}"; do
    GREP_ARGS+=(-e $exception)
done

# dump all coins except the first 3 (Bitcoin, Testnet, Regtest), exclude names with less than 4 characters
ALTCOINS=$(./common/tools/cointool.py dump -l -p -t -d T1B1 -d T2T1 -d T2B1 | grep '"name"' | cut -d '"' -f 4 | tail -n +4 | awk 'length($0)>3')
# split on newlines only
OLDIFS=$IFS
IFS="
"
for altcoin in $ALTCOINS; do
    # echo :"$altcoin":
    if strings "$1" | grep -i "$altcoin" | grep -vi ${GREP_ARGS[@]} ; then
        RETURN=1
    fi
done
IFS=$OLDIFS

if [ $RETURN -ne 0 ]; then
    echo "ERROR: Altcoin strings found in Bitcoin-only firmware."
fi
exit $RETURN
