#!/bin/sh
RETURN=0

EXCEPTIONS="decred|omni|ripple|dash|TEXT_MARGIN_LEFT|APP_CARDANO_PASSPHRASE|APP_MONERO_LIVE_REFRESH|ed25519 cardano|dash_width|dashlane|flo|mnemonic|meter|refuse|fused|enemy|cinema|syntaxerror|mix|palm"

# dump all coins except the first 3 (Bitcoin, Testnet, Regtest)
ALTCOINS=$(./common/tools/cointool.py dump -l -p -t | grep '"name"' | cut -d '"' -f 4 | tail -n +4)
# split on newlines only
OLDIFS=$IFS
IFS="
"
for altcoin in $ALTCOINS; do
    # echo :"$altcoin":
    if strings "$1" | grep -i "$altcoin" | grep -Evi "$EXCEPTIONS" ; then
        RETURN=1
    fi
done
IFS=$OLDIFS

exit $RETURN
