#!/bin/sh
RETURN=0

EXCEPTIONS="decred|omni|ripple|dash|TEXT_MARGIN_LEFT|dash_width|dashlane|flo|mnemonic|meter|refuse|fused|enemy|cinema|syntaxerror|mix|palm|UdesRsK|kcc|derive_cardano|ntity|gather|bmc|cloudflare|rsk7|map|oho|mas|uniq|numbers|aves"

# dump all coins except the first 3 (Bitcoin, Testnet, Regtest)
ALTCOINS=$(./common/tools/cointool.py dump -l -p -t -d trezor1 -d trezor2 | grep '"name"' | cut -d '"' -f 4 | tail -n +4)
# split on newlines only
OLDIFS=$IFS
IFS="
"
for altcoin in $ALTCOINS; do
    # echo :"$altcoin":
    if strings "$1" | grep -i "$altcoin" | grep -Evi "$EXCEPTIONS" ; then
        RETURN=1
    fi
done
IFS=$OLDIFS

if [ $RETURN -ne 0 ]; then
    echo "ERROR: Altcoin strings found in Bitcoin-only firmware."
fi
exit $RETURN
