#!/usr/bin/env python3
import sys


def process_firmware(filename):
    data = open(filename, 'rb').read()


def main():
    if len(sys.argv) < 2:
        print('Usage: check_firmware firmware.bin')
        return 1
    fn = sys.argv[1]
    process_firmware(fn)


main()
