#!/usr/bin/env python3
import json

fields = [
    'coin_name',
    'coin_shortcut',
    'address_type',
    'maxfee_kb',
    'address_type_p2sh',
    'address_type_p2wpkh',
    'address_type_p2wsh',
    'signed_message_header',
    'xpub_magic',
    'xprv_magic',
    'bip44',
]

coins = json.load(open('../../trezor-common/coins.json', 'r'))

print('COINS = [')
for c in coins:
    print('    CoinType(')
    for n in fields:
        if n in ['xpub_magic', 'xprv_magic']:
            print('        %s=0x%s,' % (n, c[n]))
        else:
            print('        %s=%s,' % (n, repr(c[n])))
    print('    ),')
print(']\n')
