#ifndef DSI_H_
#define DSI_H_

#include STM32_HAL_H

#define MAX_DISPLAY_RESX 240
#define MAX_DISPLAY_RESY 240
#define DISPLAY_RESX 240
#define DISPLAY_RESY 240
#define DISPLAY_COLOR_MODE DMA2D_OUTPUT_ARGB8888
#define DISPLAY_FRAMBUFFER_WIDTH 768
#define DISPLAY_FRAMBUFFER_HEIGHT 480
#define TREZOR_FONT_BPP 4

#define DISPLAY_EFFICIENT_CLEAR 1

extern uint8_t *const DISPLAY_DATA_ADDRESS;

#endif
