from micropython import const

HASH_TX_SIGN = const(0x53545800)  # 'STX'
HASH_TX_SIGN_MULTI = const(0x534D5400)  # 'SMT'

# https://xrpl.org/basic-data-types.html#specifying-currency-amounts
DIVISIBILITY = const(6)  # 1000000 drops equal 1 XRP

FLAG_FULLY_CANONICAL = 0x80000000

REQUIRED_FIELDS = {
    "common": ["fee", "sequence"],
    "payment": [["amount", "issued_amount"], "destination"],
    "set_regular_key": [],
    "escrow_create": ["amount", "destination"],
    "escrow_cancel": ["owner", "offer_sequence"],
    "escrow_finish": ["owner", "offer_sequence"],
    "account_set": [],
    "payment_channel_create": ["amount", "destination", "settle_delay", "public_key"],
    "payment_channel_fund": ["channel", "amount"],
    "payment_channel_claim": ["channel"],
    "trust_set": ["limit_amount"],
    "offer_create": [
        ["taker_gets", "issued_taker_gets"],
        ["taker_pays", "issued_taker_pays"],
    ],
    "offer_cancel": ["offer_sequence"],
    "signer_list_set": ["signer_quorum"],
    "check_create": ["destination", ["issued_send_max", "send_max"]],
    "check_cancel": ["check_id"],
    "check_cash": [
        "check_id",
        ["amount", "issued_amount", "deliver_min", "issued_deliver_min"],
    ],
    "deposit_preauth": [["authorize", "unauthorize"]],
    "account_delete": ["destination"],
}

FLAGS = {
    "account_set": {
        1: "Require Dest",
        2: "Require Auth",
        3: "Disallow XRP",
        4: "Disable Master",
        5: "Account Txn ID",
        6: "No Freeze",
        7: "Global Freeze",
        8: "Default Ripple",
        9: "Deposit Auth",
    },
    "trust_set": {
        0x00010000: "Setf Auth",
        0x00020000: "Set No Ripple",
        0x00040000: "Clear No Ripple",
        0x00100000: "Set Freeze",
        0x00200000: "Clear Freeze",
    },
    "payment": {
        0x00010000: "No Direct Ripple",
        0x00020000: "Partial Payment",
        0x00040000: "Limit Quality",
    },
    "offer_create": {
        0x00010000: "Passive",
        0x00020000: "ImmediateOrCancel",
        0x00040000: "Fill Or Kill",
        0x00080000: "Sell",
    },
    "payment_channel_claim": {0x00010000: "Renew", 0x00020000: "Close"},
}

TRANSACTIONS = {
    "TYPES": {
        "UInt16": 1,
        "UInt32": 2,
        "Hash128": 4,
        "Hash256": 5,
        "Amount": 6,
        "Blob": 7,
        "AccountID": 8,
        "STObject": 14,
        "STArray": 15,
        "UInt8": 16,
        "PathSet": 18,
    },
    "FIELDS": {
        "transaction_type": {"nth": 2, "isSigningField": True, "type": "UInt16"},
        "signer_weight": {"nth": 3, "isSigningField": True, "type": "UInt16"},
        "flags": {"nth": 2, "isSigningField": True, "type": "UInt32"},
        "source_tag": {"nth": 3, "isSigningField": True, "type": "UInt32"},
        "sequence": {"nth": 4, "isSigningField": True, "type": "UInt32"},
        "expiration": {"nth": 10, "isSigningField": True, "type": "UInt32"},
        "transfer_rate": {"nth": 11, "isSigningField": True, "type": "UInt32"},
        "wallet_size": {"nth": 12, "isSigningField": True, "type": "UInt32"},
        "destination_tag": {"nth": 14, "isSigningField": True, "type": "UInt32"},
        "quality_in": {"nth": 20, "isSigningField": True, "type": "UInt32"},
        "quality_out": {"nth": 21, "isSigningField": True, "type": "UInt32"},
        "offer_sequence": {"nth": 25, "isSigningField": True, "type": "UInt32"},
        "last_ledger_sequence": {"nth": 27, "isSigningField": True, "type": "UInt32"},
        "set_flag": {"nth": 33, "isSigningField": True, "type": "UInt32"},
        "clear_flag": {"nth": 34, "isSigningField": True, "type": "UInt32"},
        "signer_quorum": {"nth": 35, "isSigningField": True, "type": "UInt32"},
        "cancel_after": {"nth": 36, "isSigningField": True, "type": "UInt32"},
        "finish_after": {"nth": 37, "isSigningField": True, "type": "UInt32"},
        "email_hash": {"nth": 1, "isSigningField": True, "type": "Hash128"},
        "previous_txn_id": {"nth": 5, "isSigningField": True, "type": "Hash256"},
        "wallet_locator": {"nth": 7, "isSigningField": True, "type": "Hash256"},
        "account_txn_id": {"nth": 9, "isSigningField": True, "type": "Hash256"},
        "invoice_id": {"nth": 17, "isSigningField": True, "type": "Hash256"},
        "amount": {"nth": 1, "isSigningField": True, "type": "Amount"},
        "balance": {"nth": 2, "isSigningField": True, "type": "Amount"},
        "limit_amount": {"nth": 3, "isSigningField": True, "type": "Amount"},
        "taker_pays": {"nth": 4, "isSigningField": True, "type": "Amount"},
        "taker_gets": {"nth": 5, "isSigningField": True, "type": "Amount"},
        "fee": {"nth": 8, "isSigningField": True, "type": "Amount"},
        "send_max": {"nth": 9, "isSigningField": True, "type": "Amount"},
        "deliver_min": {"nth": 10, "isSigningField": True, "type": "Amount"},
        "public_key": {"nth": 1, "isSigningField": True, "type": "Blob"},
        "message_key": {"nth": 2, "isSigningField": True, "type": "Blob"},
        "signing_pub_key": {"nth": 3, "isSigningField": True, "type": "Blob"},
        "txn_signature": {"nth": 4, "isSigningField": False, "type": "Blob"},
        "signature": {"nth": 6, "isSigningField": False, "type": "Blob"},
        "domain": {"nth": 7, "isSigningField": True, "type": "Blob"},
        "memo_type": {"nth": 12, "isSigningField": True, "type": "Blob"},
        "memo_data": {"nth": 13, "isSigningField": True, "type": "Blob"},
        "memo_format": {"nth": 14, "isSigningField": True, "type": "Blob"},
        "fulfillment": {"nth": 16, "isSigningField": True, "type": "Blob"},
        "condition": {"nth": 17, "isSigningField": True, "type": "Blob"},
        "account": {"nth": 1, "isSigningField": True, "type": "AccountID"},
        "owner": {"nth": 2, "isSigningField": True, "type": "AccountID"},
        "destination": {"nth": 3, "isSigningField": True, "type": "AccountID"},
        "issuer": {"nth": 4, "isSigningField": True, "type": "AccountID"},
        "authorize": {"nth": 5, "isSigningField": True, "type": "AccountID"},
        "unauthorize": {"nth": 6, "isSigningField": True, "type": "AccountID"},
        "regular_key": {"nth": 8, "isSigningField": True, "type": "AccountID"},
        "object_end_marker": {"nth": 1, "isSigningField": True, "type": "STObject"},
        "memo": {"nth": 10, "isSigningField": True, "type": "STObject"},
        "signer_entry": {"nth": 11, "isSigningField": True, "type": "STObject"},
        "signer": {"nth": 16, "isSigningField": True, "type": "STObject"},
        "array_end_marker": {"nth": 1, "isSigningField": True, "type": "STArray"},
        "signers": {"nth": 3, "isSigningField": False, "type": "STArray"},
        "signer_entries": {"nth": 4, "isSigningField": True, "type": "STArray"},
        "memos": {"nth": 9, "isSigningField": True, "type": "STArray"},
        "paths": {"nth": 1, "isSigningField": True, "type": "PathSet"},
        "settle_delay": {"nth": 39, "isSigningField": True, "type": "UInt32"},
        "channel": {"nth": 22, "isSigningField": True, "type": "Hash256"},
        "check_id": {"nth": 24, "isSigningField": True, "type": "Hash256"},
        "tick_size": {"nth": 16, "isSigningField": True, "type": "UInt8"},
    },
    "TRANSACTION_TYPES": {
        "invalid": -1,
        "payment": 0,
        "escrow_create": 1,
        "escrow_finish": 2,
        "account_set": 3,
        "escrow_cancel": 4,
        "set_regular_key": 5,
        "offer_create": 7,
        "offer_cancel": 8,
        "signer_list_set": 12,
        "payment_channel_create": 13,
        "payment_channel_fund": 14,
        "payment_channel_claim": 15,
        "check_create": 16,
        "check_cash": 17,
        "check_cancel": 18,
        "deposit_preauth": 19,
        "trust_set": 20,
        "account_delete": 21,
    },
}
