
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecodealliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.aho-corasick]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.104"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.17"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.177"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.4"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.23"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.145"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.117"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.25.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"
