// This file is automatically generated by nem_mosaics.py -- DO NOT EDIT!

#include "nem_mosaics.h"

const NEMMosaicDefinition NEM_MOSAIC_DEFINITIONS[NEM_MOSAIC_DEFINITIONS_COUNT] = {{
	.has_ticker = true,
	.ticker = " XEM",
	.has_namespace = true,
	.namespace = "nem",
	.has_mosaic = true,
	.mosaic = "xem",
	.has_divisibility = true,
	.divisibility = 6,
},
{
	.has_name = true,
	.name = "DIMCOIN",
	.has_ticker = true,
	.ticker = " DIM",
	.has_namespace = true,
	.namespace = "dim",
	.has_mosaic = true,
	.mosaic = "coin",
	.has_divisibility = true,
	.divisibility = 6,
	.has_levy = true,
	.levy = NEMMosaicLevy_MosaicLevy_Percentile,
	.has_fee = true,
	.fee = 10,
},
{
	.has_name = true,
	.name = "DIM TOKEN",
	.has_ticker = true,
	.ticker = " DIMTOK",
	.has_namespace = true,
	.namespace = "dim",
	.has_mosaic = true,
	.mosaic = "token",
	.has_divisibility = true,
	.divisibility = 6,
}};

const NEMMosaicDefinition *NEM_MOSAIC_DEFINITION_XEM = NEM_MOSAIC_DEFINITIONS;
