//! String access collector for emulator instrumentation.
//!
//! Records every `TR` (TranslatedString) access in an in-memory bitset.
//! Enabled only when the `ui_string_collector` Cargo feature is active.
//!
//! Usage:
//! - `record(tr)` is called from `TString::map()` on every translated string
//!   access (hot path, O(1) bit-set operation).
//! - `get_and_clear()` is called via the `trezortranslate.get_string_log()`
//!   MicroPython function, which is in turn invoked by the DebugLink
//!   `DebugLinkGetStringLog` handler to retrieve (and atomically reset) the
//!   list of accessed translation keys.

use spin::RwLock;

use super::translated_string::TranslatedString;

// Ceiling division: one u64 word covers 64 discriminant slots.
const NWORDS: usize = TranslatedString::COUNT.div_ceil(64);

static STRING_LOG: RwLock<[u64; NWORDS]> = RwLock::new([0u64; NWORDS]);

/// Record a single translated-string access.
///
/// This is called from the hot path of `TString::map()`. It must be as cheap
/// as possible: a try-lock followed by a single bit-set if the lock is
/// uncontested.
#[inline]
pub fn record(tr: TranslatedString) {
    let idx = tr as usize;
    let word = idx / 64;
    let bit = idx % 64;
    // Bounds check (statically should never fail, but avoids UB if order.json
    // grows beyond expectation without updating NWORDS).
    if word < NWORDS {
        // try_write avoids deadlock if record() is somehow re-entered while the
        // lock is held (e.g. during get_and_clear()).
        if let Some(mut log) = STRING_LOG.try_write() {
            log[word] |= 1u64 << bit;
        }
    }
}

/// Return a snapshot of all recorded strings without clearing the log.
pub fn get() -> [u64; NWORDS] {
    *STRING_LOG.read()
}

/// Return a snapshot of all recorded strings and atomically clear the log.
pub fn get_and_clear() -> [u64; NWORDS] {
    let mut log = STRING_LOG.write();
    let snapshot = *log;
    *log = [0u64; NWORDS];
    snapshot
}

/// Clear the log without returning it.
pub fn clear() {
    *STRING_LOG.write() = [0u64; NWORDS];
}

/// Iterate over the set bits in a snapshot and call `f` with the name of each
/// hit `TranslatedString`.  Only available when `debug` feature is also active
/// (required for `uDebug` on the enum).
#[cfg(feature = "debug")]
pub fn for_each_name<F>(snapshot: &[u64; NWORDS], mut f: F)
where
    F: FnMut(&str),
{
    use num_traits::FromPrimitive;

    for (word_idx, &word) in snapshot.iter().enumerate() {
        let mut bits = word;
        while bits != 0 {
            let bit = bits.trailing_zeros() as usize;
            bits &= bits - 1; // clear the lowest set bit
            let idx = (word_idx * 64 + bit) as u16;
            if let Some(tr) = TranslatedString::from_u16(idx) {
                // Write the variant name into a stack-allocated buffer using
                // the uDebug impl generated by `#[derive(ufmt::derive::uDebug)]`.
                // The longest TR key is currently 60 chars; 80 is ample.
                let mut buf = heapless::String::<80>::new();
                // ufmt::uDebug for a unit-enum variant writes just the variant
                // name (e.g. "address__address"), which is exactly what we want.
                if ufmt::uwrite!(&mut buf, "{:?}", tr).is_err() {
                    // Truncation: the buffer was too small for this variant name.
                    // This should never happen with the current 80-byte capacity,
                    // but catch it in debug builds and still report the partial name.
                    debug_assert!(false, "TR key truncated - increase buffer size");
                }
                f(buf.as_str());
            }
        }
    }
}
