name: "[Bot] add to GitHub project"

on: [issues, pull_request]

permissions:
  contents: read
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  project-add-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Add new pull request to the Firmware project
        uses: actions/add-to-project@main
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          project-url: https://github.com/orgs/trezor/projects/60
          github-token: ${{ secrets.GH_BOT_TOKEN }}

  project-add-issue:
    name: Add new issue to the Firmware project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        if: github.event_name == 'issues' && github.event.action == 'opened'
        with:
          project-url: https://github.com/orgs/trezor/projects/60
          github-token: ${{ secrets.GH_BOT_TOKEN }}
