name: ClusterFuzzLite PR fuzzing

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**'

# cancel any previous runs on the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  PR:
    # run only in public repositories - fuzzer will fail in private forks (missing auth)
    if: github.event.repository.private == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # actions/checkout@v6.0.2  # needed to use the modified `run-fuzzers` action
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@404f5476ff06687c1030ecfb0832755b0c4b91bc  # google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          sanitizer: ${{ matrix.sanitizer }}
          language: c
      - name: Run Fuzzers (${{ matrix.sanitizer }})
        id: run
        uses: ./.github/actions/run-fuzzers
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 400
          mode: 'code-change'
          sanitizer: ${{ matrix.sanitizer }}
