name: Core

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize  # branch head update
      - labeled
  workflow_dispatch:
  schedule:
    - cron: '15 23 * * *'  # every day @ 23:15
  push:
    branches:
      - 'release/**'

jobs:
  param:
    name: Print hello
    runs-on: ubuntu-latest
    steps:
      - id: set_vars
        name: Print
        run: echo hello world
