name: Hardware tests

on:
  schedule:
    - cron: '15 23 * * *'  # every day @ 23:15
  workflow_dispatch:

# [Device tests](../tests/device-tests.md) that run against an actual physical Trezors.
# The device needs to have special bootloader, found in `core/embed/projects/bootloader_ci`, that
# makes it possible to flash firmware without confirmation on the touchscreen.
#
# All hardware tests are run nightly on the `main` branch,
# and also can be started manually.
#
# Currently it's not possible to run all regular TT tests without getting into
# a state where the micropython heap is too fragmented and allocations fail
# (often manifesting as a stuck test case). For that reason some tests are
# skipped.
# See also: https://github.com/trezor/trezor-firmware/issues/1371
jobs:
  legacy_device_test:
    name: Device tests T1B1
    runs-on:
      - self-hosted
      - hw-t1b1
    strategy:
      fail-fast: false
      matrix:
        coins: [universal, btconly]
    env:
      PYTEST_TIMEOUT: 1200
      T1_UHUB_LOCATION: 3-1
      T1_UHUB_PORT: 2
      T1_CAMERA: /dev/video0  # camera device
      T1_ARDUINO_SERIAL: /dev/ttyTPMB  # arduino that pushes T1 buttons
      BITCOIN_ONLY: ${{ matrix.coins == 'universal' && '0' || '1' }}
      DEBUG_LINK: 1
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # actions/checkout@v4.3.1
        with:
          submodules: recursive
      - uses: ./.github/actions/environment
      - run: nix-shell --run "bash dropbear/start.sh"
      - run: nix-shell --arg hardwareTest true --run uhubctl
      - run: nix-shell --run "uv run legacy/script/setup"
      - run: nix-shell --run "export PRODUCTION=0 && uv run legacy/script/cibuild"
      - run: nix-shell --arg hardwareTest true --run "ci/hardware_tests/t1_hw_test.sh"
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # actions/upload-artifact@v4.6.2
        with:
          name: legacy-hardware-${{ matrix.coins }}
          path: ci/hardware_tests/*.mp4
          retention-days: 7
        if: always()
