name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: log untrusted output
      run: |
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
        echo "untrusted output"
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@v1
      with:
        packages: hello,docker
        script: |
          nix-shell --run “poetry install”
          nix-shell --run “poetry run make pystyle_check”
