
#ifndef __INT_COMM_DEFS__
#define __INT_COMM_DEFS__

#define BLE_PACKET_SIZE (244)

#define COMM_HEADER_SIZE (3)
#define COMM_FOOTER_SIZE (1)
#define OVERHEAD_SIZE (COMM_HEADER_SIZE + COMM_FOOTER_SIZE)

#define EOM (0x55)
#define INTERNAL_EVENT (0xA2)
#define EXTERNAL_MESSAGE (0xA1)
#define INTERNAL_MESSAGE (0xA0)

#define INTERNAL_EVENT_INITIALIZED (0x00)
#define INTERNAL_EVENT_CONNECTED (0x01)
#define INTERNAL_EVENT_DISCONNECTED (0x02)

#define INTERNAL_CMD_SEND_STATE (0x00)

#endif
