#!/usr/bin/env bash

# script/test: Run test suite for application.

EMULATOR_BINARY="${EMULATOR_BINARY:-firmware/trezor.elf}"

set -e

cd "$(dirname "$0")/.."

if [ "$EMULATOR" = 1 ]; then
    trap "kill %1" EXIT

    "${EMULATOR_BINARY}" &
    export TREZOR_PATH=udp:127.0.0.1:21324
    "${PYTHON:-python}" script/wait_for_emulator.py
fi

"${PYTHON:-python}" -m pytest --junitxml=../tests/junit.xml ../tests/device_tests "$@"
